### ISSUE TITLE
Argument 1 passed to Spatie\Permission\Exceptions\GuardDoesNotMatch::create() must be of the type string, null given, called in C:\xampp\htdocs\blog\vendor\spatie\laravel-permission\src\Traits\HasPermissions.php on line 505

### ISSUE THREAD

**Issue by VardanBhanot** [spatie/laravel-permission#1006]
I am having problem while assigning permission to a role if some one would help me

```php
public function store(Request $request) {
    //Validate name and permissions field
        $this->validate($request, [
            'name'=>'required|unique:'.config('permission.table_names.roles').'|max:10',
            ]
        );
        $name = $request['name'];
        $role = new Role();
        $role->name = $name;

        $permissions = $request['permissions'];
        $role->save();
        
    //Looping thru selected permissions
        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail(); 
         //Fetch the newly created role and assign permission
            $role = Role::where('name', '=', $name)->first(); 
            $role->givePermissionTo($p);
    }

        return redirect()->route('roles.index')
            ->with('flash_message',
             'Role'. $role->name.' added!'); 
    }
```

**Comment by drbyte** [comment]
That may be a bug.
However, to avoid it, there are a couple things you could consider:

1. I wonder if you even need to do a role lookup with `Role::where()` at all, since you've already got the $role object from when you called `$role->save();`

2. ... or if the `$role->save()` isn't giving you the proper guard-name, I wonder if calling `Role::create` might be better?
ie:
```diff
-      $role = new Role();
-      $role->name = $name;
-      $role->save();
+      $role = Role::create(['name' => $name]);
```

3. After that, if you find you still need to do a role lookup, instead of doing your own eloquent `where`, you could use the following to properly resolve the `guard_name` property for you.
```diff
-    $role = Role::where('name', '=', $name)->first();
+    $role = Role::findByName($name);
```

**Comment by drbyte** [comment]
While attempting to create a failing test for this, I was reminded that the Role class constructor fills in the guard_name if one is not provided, so the guard_name is never null.
Thus, it would seem that your app must be overriding this package's Role model and is not firing the default constructor.
I suggest revisiting your customizations, and/or using the code optimizations I posted above.
