### ISSUE TITLE
Permission groups

### ISSUE THREAD

**Issue by kjjdion** [spatie/laravel-permission#1010]
Is there a way to group permissions together?

E.g. Let's say I have the following permissions:

Create Users
Update Users
Delete Users

I'd like to group them by "Users". So essentially, each permission would have a "group" attribute.

Do I need to modify the migrations and code myself to accomplish this, or is this a feature I simply have not discovered yet?

**Comment by drbyte** [comment]
I usually find that when people are asking for that it's because they want to do some sort of wildcard authorization granting, usually with a cascading strategy. For a pseudo-hierarchy/pseudo-grouping that allows for cascading, you could add this middleware inspired by #440 into your app: https://github.com/spatie/laravel-permission/blob/d58615ac37e822221d1c2dd269a6ef868d3248f9/src/Middlewares/CascadePermissionMiddleware.php (this link is to the v3 branch where it's slated to be included in v3 of this package at an undetermined future date). For now you'd need to put it in your app folders and change the namespace, and register the middleware to your app.

**Comment by kjjdion** [comment]
This is simply so I can group said permissions together in the UI with loops.

**Comment by drbyte** [comment]
Nothing built-in to specifically link individual permissions with a "group". 
Granted, it's totally geared around linking permissions to "roles", which in themselves are a "group".

Spatie has preferred to refrain from adding fields that the package itself doesn't use. However, you could extend/override the model and add your own fields if you needed that granular level of control.

**Comment by drbyte** [comment]
Alternatively, another strategy I've seen work well is to name your permissions akin to what I posted links for above, and then use the Translations layer in Laravel to handle putting human-friendly names into your UI for the very limited places where you ever display a permission/role "name" anywhere.
The side benefit to that is it would be instantly multilingual-ready if you did that.

**Comment by anilkreddy** [comment]
> I usually find that when people are asking for that it's because they want to do some sort of wildcard authorization granting, usually with a cascading strategy. For a pseudo-hierarchy/pseudo-grouping that allows for cascading, you could add this middleware inspired by #440 into your app: https://github.com/spatie/laravel-permission/blob/d58615ac37e822221d1c2dd269a6ef868d3248f9/src/Middlewares/CascadePermissionMiddleware.php (this link is to the v3 branch where it's slated to be included in v3 of this package at an undetermined future date). For now you'd need to put it in your app folders and change the namespace, and register the middleware to your app.

Any idea when it's gonna merge to v3?

**Comment by drbyte** [comment]
> > I usually find that when people are asking for that it's because they want to do some sort of wildcard authorization granting
> 
> Any idea when it's gonna merge to v3?

@anilkreddy While implemented a little differently than the Cascade linked earlier the Wildcard Permissions feature is already present in v2. It provides nearly the same outcome.

**Comment by drbyte** [comment]
v3
