### ISSUE TITLE
HasRoles not found

### ISSUE THREAD

**Issue by JTD420** [spatie/laravel-permission#1022]
```
[2019-02-12 04:23:10] production.ERROR: Trait 'Spatie\Permission\Traits\Hasroles' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Trait 'Spatie\\Permission\\Traits\\Hasroles' not found at /var/www/redacteddomain.tk/data/www/redacteddomain.tk/projectV3/app/User.php:13)
[stacktrace]
#0 {main}
"} 

```

I just finished moving my project from localhost to production server but it isn't working anymore... No clue why as it works locally! This is the error in my log file. Any idea what's wrong?

**Comment by JTD420** [comment]
I dont understand it. 

Doing a fresh install of Laravel on my server = working
Testing my project locally = working
Uploading my project on my server = 500 error saying errors about it being unable to find different traits such as HasRoles...

What could possibly be causing this conflict? :(

**Comment by drbyte** [comment]
Sounds like you're having issues with composer not installing things properly, or files not transferring to your server fully.

**Comment by JTD420** [comment]
Do you have any recommendations for a potential fix? I've tried reinstalling composer and re-transferring my files. I'm about to buy a whole new server this is becoming a big enough issue! 

Thanks,

**Comment by drbyte** [comment]
I'd first find out whether the package files are actually on the server.
Then I'd check whether the composer-generated autoload files are on the server.
I'd probably try running composer directly on the server.

Also, I'm generally use git for deployments, where the server does a git pull from the github repo. (followed by other deployment steps like a composer install, db migrate, etc).
This bypasses any FTP client app filters and server-side FTP upload filters.
Laravel Forge makes this very simple. Optionally Envoyer adds even more sugar to it.

**Comment by JTD420** [comment]
Thanks,

I tried this with Forge but it made it so permissions stopped working and only roles worked lol... I just removed the permission from my code and am only using roles now...

Also having issues because I need access to the db outside of localhost which is locked out by forge currently

**Comment by drbyte** [comment]
Judging from the combination of this post and your other one at #1027 it seems you have some general issues with your combination of app/server/deployment processes.
As far as "permissions don't work but roles do", you might investigate where your app has done anything to/with laravel's Gate layer.

**Comment by JTD420** [comment]
Could the issue be with the fact I pushed my entire laravel folder to git and then that's what Forge used to deploy?

Was I supposed to only upload certain files/folders so that composer would auto-install the dependencies?

Thanks

**Comment by drbyte** [comment]
Forge expects you to have Forge run `composer install` (with some standard production parameters it automatically adds to the default deploy script) to build the proper `/vendor` folder for the production environment. That means you normally would not commit the `vendor` folder to git, but you *would* commit the `composer.lock` file. The default contents of a new Laravel project's `.gitignore` should take care of not committing the vendor folder.
This is all done pretty cleanly automatically if you're using command-line git commands ... but I've sometimes seen Windows users who rely on GUI Apps for doing all their git stuff end up skipping the dot-prefixed files (like .gitignore) since they're often hidden from display. Turning on "display hidden files" can help with that. Not sure if that's what you're encountering, but I offer it in case it's a factor.
