### ISSUE TITLE
Using incorrect guard when syncing roles?

### ISSUE THREAD

**Issue by eNzyOfficial** [spatie/laravel-permission#1023]
Having trouble getting `$user->syncRoles($name);` to work using the `api` guard, I did some digging and it looks like the problem is in `Guard.php` L50

```return static::getNames($class)->first() ?: $default;```

It basically says, screw the default guard, let's just pick a random one from the config list. Is this intentional? Seems weird to just take a random (not explicitly chosen) guard over the default one. Essentially making it impossible to reach the default guard unless you hollow out the array in `auth.guards`

**Comment by drbyte** [comment]
It's not "random". It's quite specific.
It first checks the guard_name property of the model (checked both via the model and with Reflection), and if that isn't set, it uses the first defined guard, matching the model for the provider, from the config file. If that isn't found, it picks the declared default.

Back-story: There is some contention over the initial v2 design choice / interpretation of the meaning of "default guard". Right or wrong, this package made the choice that v2 would treat the config file as a higher priority than any app-overwritten "default" when selecting a guard.
And, since "fixing" that to allow the app to override that in real-time would cause breaking changes, we've deferred "fixing" that to a future major version. We've also largely decided that the next major version will also drop guard-specific mapping altogether since controlling that in userland is far more preferable. (Majority of users are duplicating permissions in multiple guards "just because this package requires it", and not because their app actually does something specifically different at the per-permission-per-guard level ... and Policies would easily take care of all those instead.)

**Comment by eNzyOfficial** [comment]
The default guards are `web` and `api` in the config, and as it takes the first it's not possible to chose which 'first' returns, right? Despite using an API route and thus setting api as the default guard, it on retrieving the role because `->first()` always returns `web`. Am I missing something?

What would you suggest would be the best way to remedy this? I don't really like the idea of hard coding the guard name into the model, but I guess this is the only way because getting to the default guard is basically not possible?

I do understand the reasoning behind the decisions you outlined though and they are definitely justified, it's just a pain in the ass ahaha.

**Comment by drbyte** [comment]
In your app, are you using multiple User models? Or just 1? 
Are you using different role/permissions "per guard", or is this guard thing even needed for your app?

If it's just 1 user model, and you don't need the polymorphism of relating roles/permissions to multiple models, and don't need per-guard-specific-permissions, `v1` of this package works swimmingly (just set composer to use `^1.17.0`). Not all of the v2 features have been backported, but I've used it with great success on multiple occasions. Using Policies to check HasRole and HasPermissionTo etc is a happy balance.
Granted, downgrading requires a bunch of manual work at the database level because the db schemas are very different. I'd drop the tables and start over.

**Comment by drbyte** [comment]
> What would you suggest would be the best way to remedy this? I don't really like the idea of hard coding the guard name into the model, but I guess this is the only way because getting to the default guard is basically not possible?

If you need to stick with v2, then the simplest approach is to hard-code the `guard_name` into the model.

**Comment by eNzyOfficial** [comment]
Awesome, I'll see what I can cobble together with the above. Thanks for the swift and helpful responses!
