### ISSUE TITLE
Cannot define guard in hasAnyPermission() method

### ISSUE THREAD

**Issue by chrisbjr** [spatie/laravel-permission#1052]
Hi, we have multiple guards in our application and when using `hasAnyPermission()` method to check for permissions, it looks like it doesn't have support in defining which guard to use. Upon checking, it only accepts the `$permissions` parameter with a splat operator.

I wanted to make a pull request to support defining the guard - which would've been very easy but seeing as the `$permissions` parameter is a splat, adding a `$guard` parameter would break compatibility with users using the splat feature.

Any ideas on how to tackle this?

Thanks!

**Comment by drbyte** [comment]
You could, instead of passing `$permissions` as strings, pass a collection of Permission objects which you've already retrieved by querying them with the required guard.

FYI: In a future version we're planning to remove guard-specific relations (ie: no longer register permissions directly to a guard by storing that in the db), since that can be handled in the app with policies.
