### ISSUE TITLE
Add permission to role by name

### ISSUE THREAD

**Issue by guidocaffa** [spatie/laravel-permission#1070]
I'm creating a CRUD to assign permissions to roles. The problem is my function it's not working, and I don't know why. Here is my code:

```
public function updateGroup(Request $request, $id)
{
    $permissions = $request;

    $role = Role::findOrFail($id);

    $role->revokePermissionTo($role->permissions()->get());

    foreach ($permissions as $permission) {
        $role->givePermissionTo($permission);
    }

    return $request;
}
```

$role->revokePermissionsTo() is working okey. The $request returned is:

`["groupsdelete","groupsedit","groupsview","groupscreate"]`

Thanks for your help!

**Comment by drbyte** [comment]
You're injecting a `Request` object as `$request`.
Then you're assigning `$permissions = $request`. This is wrong. Maybe you meant `$request->only(something)`?
You can't iterate `foreach(Request as $permission)` (which is what your code is attempting), because `$permission` in that case won't be a Permission object/name/id, so therefore you won't be able to `givePermissionTo($permission)` since `$permission` isn't a permission.
You'll need to figure out your `$permissions=$request` line, perhaps by specifying an array of permissions you meant it to reference?

**Comment by guidocaffa** [comment]
Thanks @drbyte ! this help me a lot!
