### ISSUE TITLE
Undefined index: role

### ISSUE THREAD

**Issue by IvayloGugalov** [spatie/laravel-permission#1101]
Hello,

I'm using laravel 5.8.
I runned make:auth and after that I've required "spatie/laravel-permission": "^2.37".
After that I get

> 
In PermissionServiceProvider.php line 66:
                         
  Undefined index: role  
> 

Best Regards

**Comment by drbyte** [comment]
Did you add the `HasRoles` trait to your User model?

**Comment by IvayloGugalov** [comment]
Yes I did add `HasRoles`. And also every command that I try like `php artisan --version` gives me the same error. Do you have a clue what might be the problem?

**Comment by drbyte** [comment]
When every `artisan` command is giving the same error it usually means your Laravel install is missing something, either because an installation failed or because some files have been deleted.
Or because you've created a PHP syntax error in your application's bootstrapping files such as your service providers or config files.
Sometimes the fix is as simple as running `composer dump-autoload`.

**Comment by IvayloGugalov** [comment]
Thank you for your fast response! I found the problem in my assembly. Thank you once again.
