### ISSUE TITLE
Object of class DateInterval could not be converted to int

### ISSUE THREAD

**Issue by MarwanMohamed** [spatie/laravel-permission#1152]
i get this error when i 
$role->givePermissionTo($permision);
or
$role->syncPermissions($request->permisions);

**Comment by drbyte** [comment]
You haven't given much context here. 

Possible causes that come to mind:
- you've extended the db schema and added some fields that are doing some typecasting
- the default cache interval time in the config has been altered
- you've changed laravel versions since installing the default config, and need to update your config file

The only DateInterval I can think of in this package is related to cache duration. Laravel 5.8 expects a datetime for cache duration, but used an integer in prior versions.
