### ISSUE TITLE
Defining a Super-Admin dose not work in error pages(404,500,403). 

### ISSUE THREAD

**Issue by shkhalid** [spatie/laravel-permission#1171]
I have defined a super user everything is working. But i have custom error pages. @can directive doesn't work on that pages.

` 
 Gate::before(function ($user, $ability) {
            return $user->hasRole('admin') ? true : null;
        });
`

**Comment by drbyte** [comment]
I'm not convinced this is related to this package.
I think you're encountering a limitation within your app or order-of-operations within Laravel itself.

For example, doing the following also doesn't make the @can directive work. So, I think the issue is not related to this package.

`AuthServiceProvider.php`
```diff
    public function boot()
    {
        $this->registerPolicies();

        //

+        Gate::define('demo', function($user) {
+            return true;
+        });
    }
```
and `resources/views/errors/404.blade.php`
```diff
@extends('errors::minimal')

@section('title', __('Not Found'))
@section('code', '404')
-@section('message', __('Not Found'))
+@section('message')
+    @can('demo')
+    <p>DEMO!</p>
+    @endcan
+
+    {{__('Not Found')}}
+@endsection
```
