### ISSUE TITLE
MySQL engine

### ISSUE THREAD

**Issue by webfactorybulgaria** [spatie/laravel-permission#118]
The migration doesn't set the storage engine so the default one is used (usually MyISAM).
A configuration option would be useful to explicitly set the storage engine (to InnoDB for example).

**Comment by freekmurze** [comment]
You can easily modify the migration after you have published it and before you run `php artisan migrate`.

**Comment by webfactorybulgaria** [comment]
Of course, but this adds a tedious step to the installation process. Also in my case the installation process of a new application is automated so I can't jump in between to update the migration.
If I make this optional/configurable and send you a pull request will you accept it?

**Comment by freekmurze** [comment]
Probably not, I think you should automate it in your own app.

**Comment by drbyte** [comment]
Not sure that having a switch for InnoDB would be necessary: I would think that MyISAM is actually better for these tables, since they're not transactional. They're write-once-read-many, for the most part, and thus cache quite well in the myisam default query-cache.

(Understandably there might be other reasons, not performance-related, for using InnoDB here, but they're probably more infrastructure-related.)

You can always change their storage engine after-the-fact if necessary, with `ALTER TABLE`.

Additionally, if you're wanting to use InnoDB as default, particularly for installing new stuff, why not change your server's default?

Just my 2-pence worth, things to consider.
