### ISSUE TITLE
middleware para usar permisos a través de roles

### ISSUE THREAD

**Issue by dagume** [spatie/laravel-permission#1181]
tengo un problema, deseo crear un middleware para usar permisos a través de roles pero no es posible ya que si uso este: 
Route::group(['middleware' => ['permission:publish articles']], function () {
    
});
me verifica es el usuario que tiene ese permiso y no el role que tiene ese permiso.
y nesecito que me verifique el permiso del rol

**Comment by drbyte** [comment]
1. Create the role. Example: `publisher`
2. Create the permission. Example: `publish articles`
3. Assign the permission to the role. 
4. Grant the role to the User.

Then when that user logs in, the `permission:publish articles` middleware will grant access because the User has the role, which has the permission.

**Comment by dagume** [comment]
ya realice todo los pasos pero me genera este error:
"User does not have the right permissions."
pero en la base de datos el usuario tiene el rol de "ingeniero" y ese rol tiene el permiso de "listar proyectos"

**Comment by drbyte** [comment]
How many guards are you using in your application, and why?

**Comment by dagume** [comment]
Lo de las guards aún no entiendo cual su funcionalidad, pero yo estoy desarrollando una API con graphql la guard que le puse a mis permisos fue "api", no se si ahí este el error.

**Comment by drbyte** [comment]
With v2 of this package, it expects you to define roles and permissions for each guard separately, so you've likely got them assigned to the wrong guard because Laravel's default is `web` but you're using `api`.

If your application only uses the `api` guard, you should remove your roles and permissions, then change the default in your `config/auth.php` from `web` to `api` and then recreate your roles and permissions.  Or even more, remove the `web` guard altogether:

```diff
return [

    'defaults' => [
-        'guard' => 'web',
+        'guard' => 'api',
        'passwords' => 'users',
    ],

    'guards' => [
-        'web' => [
-            'driver' => 'session',
-            'provider' => 'users',
-        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],
    ],
```

**Comment by dagume** [comment]
en mi archivo **config/auth.php**  
```
'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],

'guards' => [
        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
            'hash' => false,
        ],
    ],

```
En mi _schema.graphql_

```
type Query {
    projects: [Project!]! @all(model: "App\\Project") @can(ability: "view") @middleware(checks:["auth:api","permission:listar proyectos|ingeniero residente"])
    }
```
Al consumir el servicio me de login me return el usuario con su role y permisos:

```
{
  "data": {
    "me": {
      "id": "11",
      "name": "Nannie Wyman",
      "email": "nedra.parker@example.net",
      "roles": [
        {
          "name": "ingeniero residente",
          "guard_name": "api",
          "permissions": [
            {
              "name": "crear proyectos",
              "guard_name": "api"
            },
            {
              "name": "listar proyectos",
              "guard_name": "api"
            }
          ]
        }
      ]
    }
  }
}
```
pero al querer listar los projects me genera este error:

```
{
  "errors": [
    {
      "debugMessage": "User does not have the right permissions.",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      }]
    }
}
```
lo único que no he hecho es en la tabla ### model_has_parmissions 
asignarle ese permiso al usuario, ya que se supone que si el usuario tiene el rol ### ingeniero residente, que contiene el permiso de ### listar proyectos. No dederia generar el error

**Comment by drbyte** [comment]
You mentioned the `model_has_permissions` table. Usually people only mention that table if they have been manually adding records to the table using their own code and bypassing the methods provided by this package. When you manually edit records in tables managed by this package you run the risk of cache problems, because you need to manually reset the cache. Using the methods provided by this package will automatically reset the cache when appropriate. https://docs.spatie.be/laravel-permission/v2/advanced-usage/cache/

Your `debugMessage` mentions some UnauthorizedException text. For more troubleshooting, to make sure you know exactly which permission is being checked, edit your `config/permission.php` and set `display_permission_in_exception` to true. Then see whether the exception is related to the permission you think is being checked.

**Comment by alexaderramos** [comment]
Use API authentication, example, Sanctum

```
Route::middleware('auth:sanctum')->group(function () {
 Route::apiResource('users', UserApiController::class)->middleware(['role:admin']);
});
```
this works for me

**Comment by apithy-isidro-martinez** [comment]
> Use API authentication, example, Sanctum
> 
> ```
> Route::middleware('auth:sanctum')->group(function () {
>  Route::apiResource('users', UserApiController::class)->middleware(['role:admin']);
> });
> ```
> 
> this works for me

and the guard is `web` or `api`?
