### ISSUE TITLE
Spatie  permission not working with role

### ISSUE THREAD

**Issue by kizinho** [spatie/laravel-permission#1185]
i have an app with many roles like writer,admin,moderator.

i have a permissions like user-list,user-create,user-delete,post-list,post-delete

i have assigned some permissions to roles like admin role will have all the permissions and writer will have only post-list permission

in my controller if i do   $this->middleware(['role_or_permission:writer']);

this will work but when i used only  $this->middleware(['role_or_permission:post-list']);

this will not work but this permission is given to the role

please i need help on this , thanks

**Comment by drbyte** [comment]
1. You wrote: `$this->middleware(['role_or_permission:writer']);`

Since this is only checking for a `role`, I recommend using `role:writer` instead of `role_or_permission:writer`.

2. Similar: `$this->middleware(['role_or_permission:post-list']);`

Since this is really only checking a permission, best to use `can:post-list` instead.

I recommend always using `can` when testing for permissions. 
(ref: https://docs.spatie.be/laravel-permission/v2/best-practices/roles-vs-permissions/ )

3. Are you using guards other than `web` in your application? All the permission checks are based on the default guard, but if your application has multiple guards then you need to be more specific.

**Comment by kizinho** [comment]
am using guard web

**Comment by kizinho** [comment]
you mean $this->middleware(['can:post-list']);

**Comment by kizinho** [comment]
this is working $this->middleware(['role_or_permission:writer']);

but need to use permission on my controller using middleware but permission not working 

$this->middleware(['role_or_permission:post-list']);

how can i add this can:post-list as middleware

**Comment by kizinho** [comment]
Is like working not yet sure, my PC went off, i flushed the permission cache, will update you later

**Comment by kizinho** [comment]
is now wrking
