### ISSUE TITLE
Error on App\User

### ISSUE THREAD

**Issue by kovaiteam** [spatie/laravel-permission#1196]
We get the following error while creating(registering) an user into our application "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-4-App\User' for key 'PRIMARY' (SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`) values (4, App\User, 1))"

**Comment by drbyte** [comment]
That means you’ve already got a user registered to the rile you’re trying to add them to. 

I’m guessing you’ve been manually inserting records instead of using the methods provided by the package. 
And/or you’ve been deleting records from your database manually instead of by using the provided methods, and maybe running migrations and seeders without refreshing the database first.
