### ISSUE TITLE
abilities table not found

### ISSUE THREAD

**Issue by amisha-arya-21** [spatie/laravel-permission#1200]
Base table or view not found: 1146 Table 'db.abilities' doesn't exist. It was working before but not working after installing swiftmailer. Help required

**Comment by drbyte** [comment]
This package doesn't have an `abilities` table.

**Comment by amisha-arya-21** [comment]
> This package doesn't have an `abilities` table.

@drbyte exactly, do you have any idea why its showing this error?? it was working perfectly fine before

**Comment by drbyte** [comment]
I'm guessing you've changed your db configuration settings, it's pointing to a different database, or you've run a migration that's deleted a table, or you've added some code somewhere that's looking for a table that doesn't exist because you haven't run necessary migrations yet. 
I'm confused why you're posting about it in the Laravel-Permissions package issues repo, because it doesn't refer to a table used by this package. And you mentioned installing swiftmailer, which is also unrelated to this package. And isn't swiftmailer "already" installed by Laravel anyway? I'm confused why you'd be installing it separately.
