### ISSUE TITLE
Support multiple role and permission tables?

### ISSUE THREAD

**Issue by xlkit456852** [spatie/laravel-permission#1209]
Laravel Version: 5.5.*

Description:
Our project has two different user type (platform/brand) and they have their own role table and permission table , like this:

user tables:
administrator_platforms、administrator_brands

role tables:
role_platforms、role_brands

permission tables:
permission_platforms、permission_brands

permission_role tables:
role_permission_platforms、role_permission_brands

Is there a way to handle roles and permission in different user type independently ?

**Comment by drbyte** [comment]
I think what you're asking is covered by #1142 which is further explained in #995.

**Comment by xlkit456852** [comment]
After I try Hyn I found that it uses for more than one database , but in my case , all  tables in one database (role table and permission table etc.) ,  is Hyn still work in my case ?

**Comment by drbyte** [comment]
This package doesn't require Hyn. Hyn was used as an example of a multi-tenant approach, for which someone needed multiple role/permission tables. It's not an exact match for your situation, but was intended to help inspire you towards a solution.

**Comment by drbyte** [comment]
This package allows you to extend the Role/Permission classes, and override any necessary trait methods (ie: copy them into your user Models and customize as required), to support multiple separate user Models (and therefore tables) for storing your data.

It also allows you to store role/permission data in the default tables, since it uses polymorphic relations (and therefore stores the user Model name for each role/permission) when storing records. Using the supplied methods may mean you don't need to use as many extra tables as you've previously been using. Or not. It depends on your needs.
