### ISSUE TITLE
Give un-authenticated users permissions

### ISSUE THREAD

**Issue by SayHeyD** [spatie/laravel-permission#1216]
Is it possible to give a user who isn't logged in permissions?
Or ist it possible to create a default user in laravel?
My users should be able to make their own groups and give / revoke permissions and it would be nice if they could also enable or disable viewing posts for guests?

Thanks for your help

**Comment by drbyte** [comment]
Laravel's authorization layer only provides responses for authenticated users.

However, there's a workaround you can explore. It's not really part of this package, because it's an application setting, not a role or permission.

You'll need to create a configuration setting, or some "thing" that you can configure however your application requires, to control that guest access flag. You could store it in a database somewhere if you need it to be dynamic. There are lots of db-stored config-settings packages on Composer from which you could derive some inspiration for how to do all that.

Then, once you have a way to store that configuration setting, you can "check" that setting in various ways:

In your app, define an Authorization rule, in a service provider (you can use AuthServiceProvider, but may want make another one), and use that rule to check whether a configuration setting is set, returning a boolean response.

Alternatively, you could use a Policy. The artisan-generated `view` method (created when you pass a model to the artisan make:policy command) is a good starting point. If you make the `User $user` parameter optional (either as `?User $user` or `User $user = null`) then it will allow non-authenticated users to get a response from this method. Then have the method return a boolean based on whether your application config wants to allow guests to access that resource.

Further, since Laravel 5.8.20 there is a `viewAny` method in the generated policy, which works with guests. You could use that to return a boolean response, again checking your application config setting.
