### ISSUE TITLE
Is there any function where i can check limit of role that user can have ?

### ISSUE THREAD

**Issue by leonguyen0202** [spatie/laravel-permission#1237]
I am new to Laravel so please do not criticised about my code logic too much.
**My uses case**

I have website where user can create a group/team. In that you group, there will be 3 roles: leader, vice leader and member. Leader can create/add new vice/member but there will only one vice.

Is there any function to check if there is already a user with vice leader role in their team with this package ?

**Currently my code is this** 

        $role = CustomRole::where('name', 'vice-leader')->first();
        $team = Team::where('leader', Auth::id())->get();

        foreach ($team as $member) {
            $user = User::find($member->member);

            if ($user->hasRole('vice-leader')) {
                return redirect()->back()->withErrors(['Please do not try again thing funny!']);
            }
        }

As you can see it will always redirect back. You can mark as duplicate if there is already a question available.

**Comment by drbyte** [comment]
This package allows you to associate roles/permissions with User models (er, well by "User" models, I mean models which implement the Authenticatable contract and the HasRoles trait).
To do that it creates polymorphic relationships between roles/permissions and those User models.

By your "Team" concept you appear to be wanting to create a 3rd dimension/relationship in order to limit the number assigned combinations to another Model.
Right now you'll need to write your own code to implement that 3rd dimension.
You might find the discussion at #1135 useful for inspiration on ways you might do that.
