### ISSUE TITLE
Pheanstalk 3.2.1 requirement (We Require Running 4.0)

### ISSUE THREAD

**Issue by Ant-Pinto** [spatie/laravel-permission#1243]
I know Lumen isn't officially supported, but we're using Lumen 5.8 which requires pheanstalk 4.0, are there any plans on supporting this version? We'd love to be using Spatie for our roles/permissions system!

Also, for reference, this is what brought me here (Happening on attempted installation with composer)
    `- The requested package pda/pheanstalk (locked at v3.2.1, required as ~4.0) is satisfiable by pda/pheanstalk[v3.2.1] but these conflict with your requirements or minimum-stability.`

**Comment by drbyte** [comment]
I think you're misreading the composer message.
This package has nothing to do with pheanstalk versions.

Composer is most likely saying "locked at 3.2.1" because you've got 3.2.1 files already installed in your vendor directory. I suggest a full cleanup of your vendor directory by removing it and reinstalling things. This is safe if you've not manually edited files in your vendor dir:
```sh
rm -rf vendor composer.lock
```
Then you can run your new `composer require abc/xyz` package command, and it'll install the new package while reinstalling the rest, but without the version confusion you mentioned.

**Comment by Ant-Pinto** [comment]
Well... that seems to have done it. Thanks @drbyte I appreciate it! I'm still pretty new to Laravel, I definitely just misunderstood the message
