### ISSUE TITLE
500 on hasPermissionTo without permission existing

### ISSUE THREAD

**Issue by lukasoppermann** [spatie/laravel-permission#125]
Hey,

I am not sure this is by design but if you do `$user->hasPermissionTo('doesn't exist')` you a 500 error with: 

> PermissionDoesNotExist in Permission.php line 71:

I feel this should possibly be handled by the package as in: `return false` for the permission check and log an error in the logs, maybe?

**Comment by freekmurze** [comment]
To be precise, the package only throws the exception. It's the app the makes a `500` out of it because it isn't catched.

I was thinking about returning `false` when creating the package but I choose an `Exception` because when dealing with security it's probably a good thing to be very explicit when something goes wrong.

In most cases the permission to be added will exist.  If in your project this isn't the case, make your own `hasPermissionTo` function that eats up the thrown exception by this package.
