### ISSUE TITLE
super-admin and hasanypermission work toghether?

### ISSUE THREAD

**Issue by jviure** [spatie/laravel-permission#1267]
Hi, one question..  I ve enabled the super-admin role, it's not compatible with hasAnypermission? how can I enable it? thanks! :P

**Comment by drbyte** [comment]
`hasAnyPermission($permissions)` requires that you pass a list of permissions to check against. If it finds a `true` response for any one of those listed permissions, it will return `true`.

The Super-Admin concept, using the `Gate::before('name', closure)` approach grants whatever permissions you mention in the closure. Instead of just returning `true` from the closure, you could write some hasPermisison or hasAnyPermission conditions if you wish.

Remember: `hasAnyPermission` doesn't mean "the user has any permission in the system"; it means "has at least one of the permissions I pass to the parameter list".

**Comment by jviure** [comment]
Thanks for your answer! I need hasanypermission return to the superadmins always true, for the rest..,  whatever be.  How can I achieve it?

**Comment by drbyte** [comment]
If you are using the super-admin concept of `Gate::before()` then you will need to use `can()` instead of `hasPermissionTo`.

The equivalent if `hasAnyPermission` is `can() || can() || can()`.

It's easier to build your app around `can()` everywhere if you want super-admin capability with a central rule. Also read: https://docs.spatie.be/laravel-permission/v3/best-practices/roles-vs-permissions/
