### ISSUE TITLE
How do I add permissions on the permission table relating to the models I have?

### ISSUE THREAD

**Issue by shivajichalise** [spatie/laravel-permission#1288]
I mean if I have models as User and Media then there will be 3 main permissions each right? (Add, Edit, Delete). Should I have to add this step by step for all models (manually?) ? If so what if I have 6 or more models? Adding these step by step would be a lot trouble while having many models.

**Comment by drbyte** [comment]
> I mean if I have models as User and Media then there will be 3 main permissions each right? (Add, Edit, Delete). 

Sounds like you're building an app that directly equates its CRUD operations with permission names. I'm inclined to do all that in model policies, and not with bespoke permission names.

That said, if your app actually needs such deep level of granular control per-user-per-model then yes you'll need to make permissions that can be associated with each of those operations in order to also then assign them to individual users.

**Comment by shivajichalise** [comment]
Isn't there any way that will create the permissions automatically for each of my models? Currently I have 7 models and I have to assign permissions to each of them. Manually adding them seems to be a lot of work.

**Comment by drbyte** [comment]
> Isn't there any way that will create the permissions automatically for each of my models?

No. How would we know what exactly you wanted? Lots of apps don't require any permissions for most models, or only "some" permissions under specific circumstances. Building what's needed for your app is really up to you coding it for what your app needs.

Perhaps you need to consider using something like `Laravel Backpack`, or `Voyager`, which specifically generates all the CRUD infrastructure from boilerplate, and optionally adds permissions according to how you set it up.
