### ISSUE TITLE
Assign attributes to roles created

### ISSUE THREAD

**Issue by AniketMagadum** [spatie/laravel-permission#1321]
I have created some roles in the system like:

1) Accountant
2) Client
3) Admin
4) Bookie

I have different set of attributes for each of these users for e,g the Client has a attribute for address which others don't have and also the admin has a mobile_no attribute. There are many such custom attributes for each model. I want to know what would be the best practice for creating such a system?

I want this to be integrated with Laravel Nova.

**Comment by drbyte** [comment]
Maybe I'm misunderstanding you?  

I'm guessing that your domain's terminology treats "role" as the "type of User model". But this package treats "role" as "a text string describing a collection of permissions".

It's going to be much easier for you to put those custom "attributes" onto a User model (even if you have multiple kinds of User models), instead of trying to intermingle them with adding custom fields to this permissions package.

Apologies: I can't assist much with integrating to Nova, but I don't think that will be a problem if you put your attributes onto User models.
