### ISSUE TITLE
User roles/permissions and per-team roles/permissions

### ISSUE THREAD

**Issue by xKairu** [spatie/laravel-permission#1362]
I have user roles/permissions up and running fine, I now need to implement a team system.

The premise is that a `User` will have a `Role` named `Member`, which has a `Permission` named `own-teams`. This is the basic implementation of this package, to enforce ACL for `User`'s.

I now need the `User` to create a `Team` (`id=1`). `User` gets automatically assigned a new `TeamRole` named `Owner`, with a `TeamPermission` named `manage-posts`, denoting that this `User` can now make blog posts on behalf of the `Team` he created.

All records of `Role` and `TeamRole` should be separate. eg; The `Owner` `TeamRole` shouldn't show up when managing `Role` records, nor should it show up when managing a `Team` where `id=2`. `TeamPermission` records should be shared across all `TeamRole` records, just like all `Permission` records are shared across all `Role` records.

Is this out of scope for this package or is there a way to have extra ACL systems tacked onto the side?

**Comment by helpfulguy** [comment]
I'm looking to do something similar.  Have you come up with a way to implement this?

**Comment by drbyte** [comment]
@xKairu @helpfulguy 
There are some other issues where similar things are discussed including HasManyThrough relationships, additional pivot tables, and other custom code when extending the provided models:
#1353 
#1348 
#1187
#1186
#1135

I recall one person discussing how to leverage the existing pivot tables since they're already structured to handle polymorphic data and they were looking at just adding another model to share the same table. Not sure how that worked out for them, or whether it might be suitable for your needs.
