### ISSUE TITLE
check $user->roles against role id

### ISSUE THREAD

**Issue by ikarolesky** [spatie/laravel-permission#1369]
If i do {{ $user->roles }} it prints me:
```
[{"id":1,"name":"admin","guard_name":"web","created_at":"2020-02-12 20:50:18","updated_at":"2020-02-12 20:50:18","pivot":{"model_id":10,"role_id":1,"model_type":"App\\User"}}]
```
I want to check some info agains that ID printed inside $user->roles

Like
```
IF $USER->ROLES   ID   =  1 
THEN
.....
```

**Comment by drbyte** [comment]
```blade
@hasRole('name-of-role')
then show stuff here
@endhasrole
```

Documented here: https://docs.spatie.be/laravel-permission/v3/basic-usage/blade-directives/

**Comment by ikarolesky** [comment]
@drbyte Not quite that... :/

**Comment by drbyte** [comment]
`$user->roles` is just a Laravel `relation` object, so you can query it exactly like you would with any relation object in your app. Thus this appears to be a question about basic Laravel usage.

But, assuming you already know that, I had to assume you were actually asking a question about how this package works.

> If i do {{ $user->roles }} it prints me:

This tells me you're doing something in Blade.

Thus, I gave you an example of what this package offers in terms of Blade directives.

If you want to test against an ID, again, you can use basic Laravel syntax to test whether the `$user->roles->contains(something)`, etc.

In the absence of more context, it's very difficult to help you since it's impossible to guess what you're asking.

**Comment by ikarolesky** [comment]
@drbyte 
I was having some trouble finding the relationship between user and role.
I needed to do something with that.
But i found it and now it's all good
