### ISSUE TITLE
No results after I change User model namespace

### ISSUE THREAD

**Issue by fmrodrigues92** [spatie/laravel-permission#1379]
Hi!

I installed the package in a brand new laravel 6 and when i copy my User model from App\User.php to App\Models\User.php changing only namespace, the method hasRole() doesn't work anymore.

```
$user = \App\User::where('email', 'user@email.com')->first()->hasRole('worker'); // return true when use App\User.php

$user = \App\Models\User::where('email', 'user@email.com')->first()->hasRole('worker'); // return false when use App\Models\User.php
```

Maybe this is some bug.
Thanks!

App\User.php
```
namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}
```

App\Models\User.php
```
namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}
```

**Comment by drbyte** [comment]
Hi @fmrodrigues92 
It's not a bug with the package. It's they way Eloquent polymorphic relationships are stored: it stores the actual model class FQN in the pivot table.

So, if you change your app's architecture by altering the namespace of your models which use polymorphism you'll need to go and update the data in the pivot table to match the new model namespace. For `hasRole` the pivot table is `model_has_roles`.

There are advanced ways to bypass this using a morphMap, but that makes your app more brittle because you must maintain all the mappings yourself. If you had a lot of legacy data from an old system which you needed to retain old schema for then you could use that, but if your app doesn't need it I'd just say create a migration to rename the values in the pivot table when you deploy your next update where the namespaces have been changed.

**Comment by fmrodrigues92** [comment]
Thank you for the support. 
I haven't noticed that characteristic

**Comment by kossa** [comment]
This is old but may be can help other devs, have the same error, one application run with old namespace and new one with App\Models\User namespace, in new version I added in AppServiceProvider : 
```
use Illuminate\Database\Eloquent\Relations\Relation;

Relation::morphMap([
    'App\User' => 'App\Models\User',
]);
```
