### ISSUE TITLE
User permissions are assigned to the model instead of the specific user

### ISSUE THREAD

**Issue by gdemos01** [spatie/laravel-permission#1398]
I'm trying to give Admin permissions to a specific user by assigning a role to the user.

**The issue:** The role/permissions are assigned to the entire User Model instead of that specific user.

Keep in mind that my User Model is not using an auto-increment a number as a unieque ID. Could this be the cause of the issue?

**Code:**
 `// Creates Admin Role `
`$admin_role = Role::create(['name' => 'Admin']);`
``
// Assigning Permissions to Roles`
$admin_role->givePermissionTo($access_admin_panel);
$admin_role->givePermissionTo($change_user_roles);
``
`// Assigning role to user`
`auth()->user()->assignRole('Admin'); `

**Comment by drbyte** [comment]
This package uses Laravel's polymorphic relations to associate roles/permissions with users. It does this by associating that user's identifier with the corresponding role/permission.

There is some support for changing the id to another type instead of integer, but you must make some configuration changes on your own as well as handle any relevant migration changes to the affected tables.
This is covered in the documentation area, under "UUID".

**Comment by gdemos01** [comment]
Thank you for the fast response. 

All I had to do is change the change the 'model_morph_key' type, in the migrations, to mach the type of my User model's primary key. 

Nothing else was need for my case.
