### ISSUE TITLE
Where use User::role('operador')->get()

### ISSUE THREAD

**Issue by jpgdixon** [spatie/laravel-permission#1416]
Hi when i use User::role('operador')->get() 
this dont give me all users because that role, because in the query do:

" and `model_has_roles`.`model_type` = 'App\Models\Auth\User' " in the query mysql not work, we need use STRCMP(model_has_roles.model_type,"App\Models\Auth\User")

How i can fix this?

**Comment by drbyte** [comment]
Why is `strcmp()` necessary?

The `User::role()` method is simply calling Eloquent's `scope` feature, via the `scopeRole()` method in the `HasRoles` trait. You're free to rewrite Laravel Eloquent in that section of the code if you wish. 
But I don't see what benefit `STRCMP()` offers, because `App\Models\Auth\User` is not a binary-unsafe string to compare against.
https://github.com/spatie/laravel-permission/blob/ae48577cbf0f74c6fedd4b6eb7a55a1e40afe3ae/src/Traits/HasRoles.php#L81-L83

**Comment by jpgdixon** [comment]
Thank you

For some reason mysql doesn't return true in case of 'model_has_roles.model_type = "App \ Models \ Auth \ User"'

**Comment by drbyte** [comment]
Perhaps there's a setting your MySQL configuration that's causing that?

What Laravel/MySQL/PHP versions are you using?

Unless you fix what MySQL is doing in your environment I think you'll have problems with every Laravel app that uses polymorphic relations, since the query is generated by Laravel.

**Comment by jpgdixon** [comment]
MySQL 5.7.21
PHP 7.4.1
Laravel 6.18.2
Windows.

I fix the problem using the role id, and don't use its name. But it is not the best.

**Comment by drbyte** [comment]
It sounds like you've made significant customizations to the code, but in the absence of those details it's hard to offer additional support.

Nevertheless, I'm glad you found a workaround for your unique environmental limitations.
