### ISSUE TITLE
Suggestion: add expire time to role assignment

### ISSUE THREAD

**Issue by ariaieboy** [spatie/laravel-permission#1437]
Hi
I searched for this feature but found nothing in the project documentation.
As you know, selling a membership is one of the ways to make money on many sites.
And to implement this feature, you can easily use this library.
But the disadvantage of this library is that it cannot handle the expiration date of a role for the user.

**Comment by drbyte** [comment]
Thanks for the suggestion. 

We will not be implementing that because adding a custom field for your own application's purposes is something you can do in your own code:

- add the extra fields to your database using a migration
- add the necessary logic your application requires in order to use the data in those fields
