### ISSUE TITLE
get users where user doesn't Have any Role

### ISSUE THREAD

**Issue by el3zahaby** [spatie/laravel-permission#1472]
Hello,

How to get the list of users that doesn't Have any Role?

Thank you

**Comment by drbyte** [comment]
Since these are Laravel Eloquent relations, you can use built-in Laravel methods for interacting with them.

In the documentation you'll see mention of some of the kinds of Eloquent calls you can make regarding roles and permissions. 
https://docs.spatie.be/laravel-permission/v3/basic-usage/basic-usage/ (toward the bottom of the page is an example of `doesntHave()`)
