### ISSUE TITLE
Suggestion for implementing Permissions with Model Relation

### ISSUE THREAD

**Issue by rlvillacarlos** [spatie/laravel-permission#1475]
I would like to ask for some recommendation in implementing a permission setup involving model relations.

Consider the set-up where we have two models Teachers and Subjects. So I setup a many-to-many relation in these models. The idea is only the assigned teacher can do actions (view, update, edit, etc) to the assigned subjects. Now, I am thinking if I should use wild card permission to restrict the access of teachers. For example, if a teacher A is assigned to subject with id `101` then assign to A the permission `subject.101.view` to allow viewing or `subject.101.*` for full control.

Is this setup too much? Should I just assign permission to allow actions for subjects, e.g. `subject.view`  (or `subject.*`) then just inspect the relation of the models to determine if the subject is assigned to the teacher?

Or are there better permission setup?

**Comment by Luizgpp** [comment]
Hello @rlvillacarlos ,
I need something like that too.

I need one more Model (sector) to grant role and permissions.


Like that:

User Jhon - Role supervisor - Sector Back Develop - permission 1,2 and 3

But Jhon can work at  Sector Front Develop and your Role just worker with permission 1.


So
User 1
Role 1
Sector 1
Permission - 1 - 2 - 3

And

User 1
Role 3
Sector 3
Permission 1

**Comment by drbyte** [comment]
@rlvillacarlos @Luizgpp how did you end up solving this in your app?

**Comment by ymforeal** [comment]
Hello @rlvillacarlos,

I would highly recommend you go with permissions like subject.view, subject.edit which would be much clean and query efficient.
Basically, all the permissions are string based, in your case, permissions are generated with subjects and actions(view, edit, delete etc.) which can be stored in two different tables and maintained separately. So whenever you create a new subjects, an event can be fire up to auto create permissions with your newly created subject and selected actions.
Otherwise, you gotta take has many through pivot relationship which isn't even covered by laravel mysql relashionship.
