### ISSUE TITLE
Truncating all Roles

### ISSUE THREAD

**Issue by gcnu1** [spatie/laravel-permission#1500]
Hello,

is there anyway to truncate all roles?

for example, when running seed, i just want to remove all existing roles to be sure..

**Comment by drbyte** [comment]
There are a few ways, each with their benefits and limitations:
- Since `roles` are just Laravel Eloquent objects, you could load all objects and loop through them to delete them one by one using `->delete()` on each object. This is slow, but calls any `deleting` and `deleted` events your app may have associated with those models.
- You could [mass-delete](https://laravel.com/docs/master/eloquent#deleting-models) them, but this wouldn't fire any events.
- You could [truncate the table](https://laravel.com/docs/master/queries#deletes) but sometimes this throws database errors on foreign keys if there are still users in your db associated with them.
- You mentioned `seeding`. If you mean seeding for tests and new installations, then all this is much simpler: just use `php artisan migrate:fresh` to [delete all the tables and start clean](https://laravel.com/docs/master/migrations#rolling-back-migrations). You can run your seeders after that (or with `--seed` parameter on the same command)

**Comment by gcnu1** [comment]
Hello,
thanks for the response.

I have tried 3rd option and it is throwing foreign key errors

I want to do it because, if someone runs `php artisan migrate --seed` more than one time, i want to delete all existing roles,

but if there is a way to prevent re-creating role, then also it works for me
i.e. something like `findOrNew` or `firstOrCreate` methods.

**Comment by drbyte** [comment]
Yes, the models have a `findOrCreate` method:
https://github.com/spatie/laravel-permission/blob/782af0045cf95ae9eaf8d96b338349e1572a4cd2/src/Models/Role.php#L106-L125

**Comment by gcnu1** [comment]
Thank you, that fixed it :) (i was passing array earlier)

Also, i see that it is adding `web` guard by default, that means it doesn't work with api routes?

thanks.
