### ISSUE TITLE
Soft Delete Role not working in my app

### ISSUE THREAD

**Issue by amitkolloldey** [spatie/laravel-permission#1505]
I am trying to extend the Role model as instructed https://docs.spatie.be/laravel-permission/v3/advanced-usage/extending/#extending to add soft delete trait to the role. But the feature is not working.

Here is my `config/permission.php` file:

```
<?php
return [

    'models' => [
        /*
         * When using the "HasPermissions" trait from this package, we need to know which
         * Eloquent model should be used to retrieve your permissions. Of course, it
         * is often just the "Permission" model but you may use whatever you like.
         *
         * The model you want to use as a Permission model needs to implement the
         * `Spatie\Permission\Contracts\Permission` contract.
         */

        'permission' => App\Permission::class,

        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * Eloquent model should be used to retrieve your roles. Of course, it
         * is often just the "Role" model but you may use whatever you like.
         *
         * The model you want to use as a Role model needs to implement the
         * `Spatie\Permission\Contracts\Role` contract.
         */

        'role' => App\Role::class,

    ],
```

and Role Model:

```
class Role extends \Spatie\Permission\Models\Role
{
    protected $table = 'roles';

    use SoftDeletes;

    protected $fillable = [
        'label',
    ];

    /**
     * @param $value
     * @return string
     */
    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->diffForHumans();
    }

    /**
     * @param $value
     * @return string
     */
    public function getUpdatedAtAttribute($value)
    {
        return Carbon::parse($value)->diffForHumans();
    }
    
}
```

**Comment by drbyte** [comment]
> but it's not working

Sorry, there's nothing in your post that explains what you mean by "it's not working".  

Surely you tried to do something and expected a certain result but got a different result. What were those things? 
If you want help with something it's very important that you provide enough detail for the problem to be rebuilt in a new app in order to replicate the problem. Otherwise it's all just guesswork.

**Comment by amitkolloldey** [comment]
I was trying to add softdelete functionality to Role model by extending the `Spatie\Permission\Models\Role`. But when I try to delete any role it gets deleted permanently. Seems like it's firing the `Spatie\Permission\Models\Role` model even after defining the custom model in the config file.

I tried `config:clear` but no luck.

**Comment by drbyte** [comment]
Your app is apparently using the wrong model.

In situations like this it's always good to create a new app to do the functionality you're expecting, in order to isolate the root cause of the issue in your larger app.

Here's one I created to demonstrate that soft-deletes on a custom model work correctly. You can see it in the passing tests.
https://github.com/drbyte/permissions-soft-deletes-custom-model/

Tests Passing: https://github.com/drbyte/permissions-soft-deletes-custom-model/runs/782440830
Commit history: https://github.com/drbyte/permissions-soft-deletes-custom-model/commits/master
Tests: https://github.com/drbyte/permissions-soft-deletes-custom-model/blob/master/tests/Unit/PermissionTest.php
Custom model: https://github.com/drbyte/permissions-soft-deletes-custom-model/blob/master/app/Role.php

**Comment by mohsenmojadam2019** [comment]
This is the documentation for v3 but the latest version is v5. You can switch versions in the menu on the left. Check your current version with the following command:

composer show spatie/laravel-permission
Extending
Extending User Models
Laravel's authorization features are available in models which implement the Illuminate\Foundation\Auth\Access\Authorizable trait.

By default Laravel does this in \App\User by extending Illuminate\Foundation\Auth\User, in which the trait and Illuminate\Contracts\Auth\Access\Authorizable contract are declared.

If you are creating your own User models and wish Authorization features to be available, you need to implement Illuminate\Contracts\Auth\Access\Authorizable in one of those ways as well.

CHILD USER MODELS
Due to the nature of polymorphism and Eloquent's hard-coded mapping of model names in the database, setting relationships for child models that inherit permissions of the parent can be difficult (even near impossible depending on app requirements, especially when attempting to do inverse mappings). However, one thing you might consider if you need the child model to never have its own permissions/roles but to only use its parent's permissions/roles, is to override the getMorphClass method on the model.

eg: This could be useful, but only if you're willing to give up the child's independence for roles/permissions:

    public function getMorphClass()
    {
        return 'users';
    }
Extending Role and Permission Models
If you are extending or replacing the role/permission models, you will need to specify your new models in this package's config/permission.php file.

First be sure that you've published the configuration file (see the Installation instructions), and edit it to update the models.role and models.permission values to point to your new models.

Note the following requirements when extending/replacing the models:

EXTENDING
If you need to EXTEND the existing Role or Permission models note that:

Your Role model needs to extend the Spatie\Permission\Models\Role model
Your Permission model needs to extend the Spatie\Permission\Models\Permission model
You need to update config/permisison.php to specify your namespaced model
