### ISSUE TITLE
can function work with ?

### ISSUE THREAD

**Issue by whfamily2006** [spatie/laravel-permission#151]
`Auth::user()->can($permission)` works with user_has_permissions, but not working with permission_roles...

i have 
Role: Staff, SuperAdmin
User: staff_user, admin_user
Permission: user_actions

i am assigning permission [user_action] to Role staff but its not working with can() function...

**Comment by whfamily2006** [comment]
May be i am wrong, i think i figure out this issue. @can  work properly and role wise permission also working fine... but the issue raised in this following situation.

Step 1: Create Role
Step 2: Create User and assign role too
Step 3: Create Permission
Step 4: Assign Permissions to specific role.

if assigned permission to my role by using these above steps than the following code not working.

`@if(\Auth::user()->can( 'show_campus_menu'))`
`       < li id = "admin-setup-campus">< a href = "{{url('admin/campus')}}"><i class = ""></i> Campus</a></li>`
`@endif`

`@can( 'show_campus_menu'))`
`       < li id = "admin-setup-campus">< a href = "{{url('admin/campus')}}"><i class = ""></i> Campus</a></li>`
`@endcan`

and after that when i create new role or permission then my previous assigned permissions to role working fine... 
I think problem in caching...

**Comment by freekmurze** [comment]
After adding permission or roles to a user it's best to retrieve a fresh copy of the user before calling `can` in the same request.

```php
$user = Auth::user();
$user->givePermissionTo('edit');
$user = $user->fresh();
if ($user->can('edit')) {
   ...
}
```

If this does not work in your project, could you please PR a failing test for me to look at?

**Comment by whfamily2006** [comment]
**Sorry** @freekmurze  i am not good in tests. that's why i write the complete situation.

**Comment by mtb3** [comment]
Hello, I came across this issue (as well as #134) while researching my own issues using gates (i.e., calls to `can`) after adding or removing permissions from a role.

What I have discovered is that one must always be sure to use `laravel-permission`'s `givePermissionTo` / `revokePermissionTo` methods when adding or removing permissions, to ensure that `laravel-permission`'s cache is updated properly:
- Direct database manipulations bypass any possibility for laravel-permission to update the cache
- Even when making changes via Eloquent models (implementing the `Role` / `Permission` contracts), the laravel-permission `RefreshesPermissionCache` trait does _not_ apply to adding/removing associations between objects

@freekmurze I suppose one hypothetical/possible change to laravel-permission itself would be to define the gates to look up the permission by name on each invocation, by implementing `registerPermisisons` in `PermissionRegistrar` as follows, calling `hasPermissionTo($permission->name)` instead of `hasPermissionTo($permission)`:

```php
    public function registerPermissions()
    {
        try {
            $this->getPermissions()->map(function ($permission) {
                $this->gate->define($permission->name, function ($user) use ($permission) {
                    return $user->hasPermissionTo($permission->name);
                });
            });

            return true;
        } catch (Exception $e) {
            Log::alert('Could not register permissions');

            return false;
        }
    }
```

This would, however, make gates less efficient -- and would somewhat/largely defeat the purpose of caching.

**Comment by freekmurze** [comment]
Closing this for now
