### ISSUE TITLE
Why middleware __construct does not work?

### ISSUE THREAD

**Issue by jeanali** [spatie/laravel-permission#1526]
I have these permissions in database:

`employee_read|employee_create|employee_update|employee_delete`

I put the middleware like the package said in Kernel, and I give the employee just read and delete permission, but when I'm trying to enter to create the page opened! even I put the __construct in controller:

<img width="1120" alt="Screen Shot 2020-07-12 at 3 06 19 AM" src="https://user-images.githubusercontent.com/67483209/87236055-b388b300-c3ec-11ea-9c3c-efef2c694ddb.png">

**Comment by drbyte** [comment]
It's working exactly as intended.

> I give the employee just read and delete permission, but when I'm trying to enter to create the page opened!

You've given read and delete permission. Okay.

> `$this->middleware('permission:employee_read|employee_create|employee_update|employee_delete');

This means "if they have any of these permissions, let them in".

So, since they have read and delete, and you're checking for any of (read or create or update or delete), they are allowed in.

**Comment by jeanali** [comment]
So what's the solution for my case? now I'm using ` abort_unless(Gate::allows('employee_index'),404);` at the beginning  of each method and that's so messy!

**Comment by drbyte** [comment]
> using abort_unless() ... at the beginning of each method

Sounds like a strong reason to use Laravel's Model Policies feature, and put your permission checks in there. 
https://docs.spatie.be/laravel-permission/v3/best-practices/using-policies/

**Comment by jeanali** [comment]
Yeah I thought about this, but the problem I need Laravel Policies for something else for each controller :)
So any other suggestions please ?

**Comment by drbyte** [comment]
> but the problem I need Laravel Policies for something else for each controller :)
> So any other suggestions please ?

Base: your controller has methods for which you wish to test for authorization before executing those methods. You say you are already using Model Policies in those methods.

So you have 2 options:
- In your existing policies for those methods, combine these permission checks into your existing policy logic.
- Or, `abort_unless` is perfectly suitable since it's explicit about the exact (but different) permission tested in each controller method


As far as this package, it's working as expected. The challenges you're facing are related leveraging Laravel's features to support your unique app requirements.
