### ISSUE TITLE
Escape syntax causes permissions inaccessibility via roles

### ISSUE THREAD

**Issue by basherr** [spatie/laravel-permission#1531]
Hi Support, I just find out the following bug where **Backslahs (\\)** is stripped while querying for `permission` via `role`.

**Version**
Larvel/Framework: ^7.0
Spatie/Laravel-permission: ^3.13

**Database**
Mysql

[getPermissionsViaRoles](https://github.com/spatie/laravel-permission/blob/master/src/Traits/HasPermissions.php#L295)
```
$this->loadMissing('roles', 'roles.permissions')
            ->roles->flatMap(function ($role) {
                return $role->permissions;
            })->sort()->values();
```
The first query `$role->permissions` produces is:
```
SELECT `roles`.*, `model_has_roles`.`model_id` AS `pivot_model_id`, `model_has_roles`.`role_id` AS `pivot_role_id`, `model_has_roles`.`model_type` AS `pivot_model_type`
FROM `roles`
INNER JOIN `model_has_roles` ON `roles`.`id` = `model_has_roles`.`role_id`
WHERE `model_has_roles`.`model_id` in (1) AND `model_has_roles`.`model_type` = "App\User"
```

The above condition will not work due to the `Backslash(\\)` not stripped for the condition `model_has_roles.model_type = "App\User"`

**ACTUAL BEHAVIOR**

- The **Permissions** collection will always be empty when fetched through **Role.**

**EXPECTED BEHAVIOR**

- Assigned **Permissions** to the **Role** must be returned in the collection.

**Stripping Solution**

`model_type LIKE 'App\\User' ESCAPE '|'` OR `model_type LIKE 'App\\\\User'` can be used to avoid this behavior.

Here's a good read on [Stackoverflow](https://stackoverflow.com/questions/14926386/how-to-search-for-slash-in-mysql-and-why-escaping-not-required-for-wher)

**Comment by drbyte** [comment]
This package's tests cover that section of code, and return good results.
Thus this symptom appears to be caused by something unique to your environment.

The code this package runs here is simply leveraging Laravel core features. If you believe there is something wrong with Laravel you should explore the Laravel repositories to see if others have discussed concern about this, particularly with regard to whatever is unique about your own environment (perhaps it's your OS?), and if you believe there is a bug in Laravel you should report the matter to Laravel via their support channels, include example applications with failing tests so they can recreate the problem in order to fix it.

**Comment by pista7** [comment]
Hi there @basherr 

I was testing a fresh Laravel and Backpack (PermissionManager, which uses laravel-permission), and ran into the same problem. Query returns nothing so access is denied. Running on:

- Windows 8.1
- Laragon 4.0.16 environment: Apache 2.4.35; MySQL 5.7.24; PHP 7.4.9

Any further comments? I would appreciate...
Best regards,
