### ISSUE TITLE
Unable to clear the permissions cache

### ISSUE THREAD

**Issue by jamesbhatta** [spatie/laravel-permission#1536]
I am getting error as  **unable to flush cache**  while clearing the permissions cache using the command `php artisan permissions:cache-reset` 

I tried clearing the application cache as well using `php artisan cache:clear`. But still the same error.
Then I tried the following:

```
Route::get('clear-permissions', function () {
    return (app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions())
        ? "Cleared"
        : "Error while clearing cache";
});
```

And still the cache was not cleared.

I am using seeder to create roles and permissions and running `app()[PermissionRegistrar::class]->forgetCachedPermissions();`  in seeder. Am I doing any mistakes here? If not then what might be causing this issue.

**Comment by drbyte** [comment]
> I tried clearing the application cache as well using `php artisan cache:clear`. But still the same error.

Given that that affects the entire Laravel application, and not just this package, it sounds like something wrong in your environment/app/configuration, and not with this package.

**Comment by jamesbhatta** [comment]
I don't mean that `php artisan cache:clear` gives error. I does executes successfully but still the permissions cache doesn't get cleared.

**Comment by drbyte** [comment]
> I don't mean that `php artisan cache:clear` gives error. I does executes successfully but still the permissions cache doesn't get cleared.

That doesn't make sense: since calling `php artisan cache:clear` resets Laravel's entire cache, and this package uses Laravel's cache, then calling `php artisan cache:clear` will clear this package's permissions cache.

If `php artisan cache:clear` is not clearing Laravel's cache, then you have a problem in your Laravel app.

Alternatively, perhaps all the caches are indeed clearing correctly, but you have other code that is instantly adding things to the cache.

**Comment by jamesbhatta** [comment]
Yeah absolutely right.

**Comment by poseso** [comment]
php artisan cache:forget spatie.permission.cache
