### ISSUE TITLE
Deploying permissions logic to clients

### ISSUE THREAD

**Issue by tomaslucena** [spatie/laravel-permission#1546]
This is not a direct issue with the package, I am facing a problem and I would like to see if you offer assistance. I check in your official page and it says I should post here.

I am building a web app. The idea is then selling it to different users, so they will be able to use the app but they should not be able to set permissions, as it is only for the development part. The user can not set but they can see... so they can create their own roles and assign their own permissions to them.

If I have 1 client, managing the table of permissions wont be an issue, but if I get more clients (and I really hope I do :P ) then deploying to each of them the permissions can be really problematic.

So I have come with this idea of saving the permissions in a parallel sqlite (read only) and then deploy this db to the production environment of the client, the thing is that I still need to save the roles on the in the client DB, so they can edit and assign permissions at will. The thing is that it does not work because the package break if I have 2 different DBs for permissions and roles.

Well I hope you can guide me with an idea so I can still use this awesome package.

**Comment by drbyte** [comment]
Sounds like a common multi-tenancy scenario, where you want tenants to control roles/permissions within their own domain, independent of other tenants. In this case, use this package within each domain, with its database tables being part of each tenant.

As for "other" permissions controlled "by the app", you mentioned the idea of having a parallel db for core permissions. That's certainly doable as well, but you will need to namespace things creatively in order to identify different db connections for different sets of roles/permissions.
Alternatively, if the users can't "set" these permissions, and they're not really assigned to "users", why not just make them be controlled as application logic?  In an Auth ServiceProvider you can define Gate abilities and declare their logic there. Or you can use Model Policies if relevant.

**Comment by tomaslucena** [comment]
@drbyte thanks a lot for your answer!

Yes, is a multi-tenancy scenario as you describe. The thing is that permissions can not be created or edited (only us developers can, so then we use it on the code)... Permissions can only be assigned to roles, so basically permissions can and should be shared across all tenants but relationship between permission and roles has to be achieved locally by each of the tenants.

I could not achieve this yet but will keep investigating following your advice.

**Comment by drbyte** [comment]
What about divorcing the permissions feature from the roles feature? 
ie: let the package (each tenant) assign roles to users, but do nothing with permissions in this package.
And then in your application, define all your permissions in code, eg your own new file like AppAuthServiceProvider or AppPermissionsProvider (which is just a service provider).
Then each permission would be "defined" to "check whether the user has the Role that it needs.  (this is kinda what the package does internally with db queries, but you would do it in code instead of in db).

Example: 
For each tenant db, the App creates the tables for this package, and seeds the Roles you've created for the app. 
But no seeding of any permissions.
There are NO permissions tied to any roles in this package.

Your tenants can assign roles to any of their users however they need to.

Then in your application code, you write PHP code to define each permission. And the "logic" for each permission is to check whether the User has the Role (eg: the role that you would normally assign the permission to). (eg: $user->hasRole('foo'))

This way all the parts of your application can still use `$user->can()` or `@can()` to check for "permission", but all those permissions are found in PHP code in your AppPermissionProvider.

An example of permissions in the AppPermissionProvider might be:
```php
<?php
namespace App\Providers;

use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;

class AppPermissionProvider extends ServiceProvider
{
    public function boot()
    {
        Gate::define('print attendance report', function ($user) {
            if ($user->hasRole('office manager')) {
                return true;
            }
        });

        Gate::define('pay invoices', function ($user) {
            if ($user->hasAnyRole(['Treasurer', 'President'])) {
                return true;
            }
        });

    }
}
```

In some ways this gives you greater flexibility than this package would offer, because you could combine additional checks in each of these definitions in addition to checking whether the user has been assigned to a given role.

(You would register this AppPermissionProvider in config/app.php where you register other ServiceProviders for your App.)

**Comment by tomaslucena** [comment]
@drbyte I understand and thats exactly what I am gonna try now!

It will be a bit more complex because I want my clients to also customise their own roles, probably I will ship the app with some prefix roles like Admin and then allow the to customise a few more.

But now with you info I understand a bit more and will see if I can achieve it.
