### ISSUE TITLE
Role name formatting, docs show mixed

### ISSUE THREAD

**Issue by Braunson** [spatie/laravel-permission#1547]
After reading the docs, the role name is shown in a mixed number of ways. What is the suggest naming method.

- `Admin` or `admin`
- `Super Admin` or `super admin` or `super_admin` or `superAdmin`

I'm just curious what would be recommended as the guide shows a few different variations.

**Comment by drbyte** [comment]
The `name` parameter for Roles and Permissions is just a string (typically Eloquent treats it as `varchar(255)`.
It can be whatever you want it to be. That way it suits whatever your app's naming conventions may be.

I've seen lots of opinions on the best approach. 
Sometimes dev teams opt for "no spaces" so that double-clicking on a name in their app code in their editor highlights the whole thing, rather than having to be sure to highlight multiple words before copy/pasting for something.

Sometimes they opt for all-uppercase so that it's obvious in code.

Sometimes they opt for "Capitalize Each Word" so that the name can be presented to the end-user in a way that doesn't require translation for meaningful display.

It really depends on your needs. Whatever you do, I recommend sticking with just one convention, so that you don't have to guess what it should be.

**Comment by Braunson** [comment]
@drbyte Thanks. It was more I noticed various styles throughout the documentation. I personally like going with the slug style i.e. `super-admin`.
