### ISSUE TITLE
givePermissionTo causes the error SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `db`.`model_has_permissions`.`permission_id` at row 1 (SQL: insert into `model_has_permissions` (`model_id`, `model_type`, `permission_id`) values (24, App\User, ))

### ISSUE THREAD

**Issue by giacomok** [spatie/laravel-permission#1568]
Hi,  
I have a permission table with `permission_id` as id field.  
When I try to execute this code:

    $user->givePermissionTo('my permission');

I get this error ('my permission' exists in the `permission` table):

> SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `db`.`model_has_permissions`.`permission_id` at row 1 (SQL: insert into `model_has_permissions` (`model_id`, `model_type`, `permission_id`) values (24, App\User, ))

**Comment by drbyte** [comment]
The `model_has_permissions` table for this package does not have timestamps, but it appears you have added them manually to the migration. If you're doing that then you will also need to override the package code accordingly.

**Comment by giacomok** [comment]
This is the code of the `migration`:

    Schema::create($tableNames['model_has_permissions'], function (Blueprint $table) use ($tableNames, $columnNames) {
        $table->unsignedInteger('permission_id');

        $table->string('model_type');
        $table->unsignedBigInteger($columnNames['model_morph_key']);
        $table->index([$columnNames['model_morph_key'], 'model_type', ]);

        $table->foreign('permission_id')
            ->references('id')
            ->on($tableNames['permissions'])
            ->onDelete('cascade');

        $table->primary(['permission_id', $columnNames['model_morph_key'], 'model_type'],
            'model_has_permissions_permission_model_type_primary');
    });

There are not timestamps.

**Comment by drbyte** [comment]
> `SQLSTATE[22007]: Invalid datetime format:`

That message is saying you were trying to insert "something" into a `datetime` field that wasn't a datetime value. 

That's why I commented about the datetime fields.

Perhaps you pasted 2 errors at one time?

Regarding the second part of it:

> `1366 Incorrect integer value: '' for column db.model_has_permissions.permission_id at row 1 (SQL: insert into model_has_permissions (model_id, model_type, permission_id) values (24, App\User, ))`

That shows that you're inserting a blank string (`incorrect integer value ''`) into the `permission_id` field. You can see that it is indeed blank.

Therefore something in your application is trying to pass either a blank or empty string instead of an integer for the permission_id. Did you change the column types in the database for the `permissions` table? 
Perhaps instead of `givePermissionTo('string name')` you might need to first look up the permission from the database using `$permission = Permission::findByName(.....)` and then `givePermissionTo($permission)` so that it uses the object instead of having to do its own lookup.

**Comment by kieuro** [comment]
> Still, at the moment is imposible change primary keys `id` for custom ones

it possible
