### ISSUE TITLE
[Feature Request] Ability to add permission to specific module/model

### ISSUE THREAD

**Issue by lambasoft** [spatie/laravel-permission#1571]
I know we can name a permission "view reports", "edit reports", "delete reports". But it would be much cleaner and simpler if we could have a module <-> permission relation, where we can assign a permission to a module/model then assign the combination to a role.

**Comment by drbyte** [comment]
It seems you're essentially describing building a bridge between this package's role/permission models and enforcing those rules for a specific model, but by abstracting all of it away from the model itself.

I tend to agree with @tabacitu that this is very similar to what Laravel's Model Policies are for, but perhaps adding more boilerplate for it, or hiding it in another layer such as a package of controllers and extended models and some policies. 

Given that it would probably need to be highly opinionated, or extremely complex with a lot of overhead in order to make it very generic, I think it's not something that we will implement inside this package. It may indeed make a good idea for another package you could consider building.

If you're looking for some boilerplate for using this package with [Laravel's Model Policies[(https://spatie.be/docs/laravel-permission/v3/best-practices/using-policies), here's a rudimentary implementation/example of it for Laravel 7: https://github.com/drbyte/spatie-permissions-demo/blob/master/app/Policies/PostPolicy.php
It's not a master template for "all things about model policies", nor a complete implementation. Just an example starting point so that you don't have to feel like you're starting with a blank canvas.

Additionally, while also not directly tied to any specific model (other than by any wiring you do in your app), the [Wildcard Permissions feature](https://spatie.be/docs/laravel-permission/v3/basic-usage/wildcard-permissions) may offer a different way of thinking of the subject of permissions in relation to models.
