### ISSUE TITLE
Get user permissions from another application 

### ISSUE THREAD

**Issue by mjkarpinski** [spatie/laravel-permission#1578]
Hi, 
First of all, thanks for a great package! 
We are currently trying to figure out best approach to our permissions across multiple services, and we could use some help.

We have an api that has laravel-permissions installed, and multiple apps that are consuming data from it. The issue we are having, is how do we check permissions on those other apps that don't have laravel-permissions installed. 
We can of course check user object, and it does contain all the permissions - but is there a smarter way of doing this? Maybe there is a repo, that already has this functionality? 

Since we have multiple services that are consuming the API, we are trying to find solution, that will be easily transferred to other projects.

I found a similar question on issue tracker (https://github.com/spatie/laravel-permission/issues/864) for laravel-permissions, but the author never answered questions asked by @drbyte, so since it's a similar question, I'll answer them:

- What are the two systems?
- API and website that consumes API

- How do they relate to each other?
- Website is sending requests to grab the data from API

- How do they interact?
- As above - pretty simple scenario

- How are permissions used on each?
- Currently we check permissions on API side only  - so user makes a request, it goes to our website, which then sends a request to API with user attached. 

- What is the business problem you're trying to solve? 
- We have parts of the website that are accessible only if user has a given permission. We feel that just checking '$user->permissions' array may not be correct solution.

Thanks!

**Comment by drbyte** [comment]
I must be missing something, because this doesn't sound very complicated.

If your API application contains all the necessary information and is the single source of truth, and each client that connects to the API must identify itself to the API in some way, then since the API then knows which user it's referring to then it also knows whether that same API call has permission (via the user) to do whatever you're asking about. 
Thus in the API application all the usual $user->can() and $this->authorize() calls work as usual.
If something is denied due to insufficient permissions, you can send a denial response such as 403 or whatever is best suited.

Your API application must always enforce the permissions rules.
You could let your client/web app "ask" for the user's permissions, but be careful not to give too much in response to that, ie: don't give it a list of all permissions they have. Better to ask the API for whether the user has a specific permission that the client wants to use, as this prevents a malicious user for learning anything that could put your application at risk. Still, again, your API application must still always enforce permissions, and must always assume the web/client app is untrustworthy, because javascript and responses can be tampered with and spoofed.
Again: the API application (with the database, with all the actual official permission rules) must always re-verify and enforce the rules regardless what the web client submits.
