### ISSUE TITLE
Gate::before only gets called for permissions that are not assigned to the role of current user

### ISSUE THREAD

**Issue by atiqsamtia** [spatie/laravel-permission#1582]
I've put a breakpoint on Gate::before and it only gets trigger for permissions that are not assigned to the role of the current user. 

I have a scenario where I was to reject some permissions on the bases of the current user column with the same role. Gate::before seems the best place to do so but it does not trigger for any permission which is already assigned to the role.

Example

These are permissions for a role
- Franchise Owner
  - create-booking
  - delete-booking
  - create-event
  - delete-event

This is my use case 

if currentUser->type = **both**  => all role permissions

if currentUser->type = **booking** => deny all **event** related permissions

if currentUser->type = **event** => deny all **booking** related permissions

We did this in Gate::before but that does not get trigger for all permissions

I'm really stuck on this one, as our whole application is built on permissions

**Comment by drbyte** [comment]
> Gate::before only gets called for permissions that are not assigned to the role of current user

I can't substantiate that claim.

> if currentUser->type = booking => deny all event related permissions
> if currentUser->type = event => deny all booking related permissions

This package doesn't offer "deny certain permissions after already granting them".
While you're trying to do that at the Gate using `before`, and it may be possible there (I haven't tried to recreate your app), a more straightforward way to architect might be:

`if currentUser->type = booking => grant all booking related permissions` (instead of `deny all event related permissions`)

Another option to consider, and exists for the reason that your sort of scenario raises, is to also employ a `Gate::after` rule to do additional overrides/denials. See the docs for a link to an article Freek wrote about when `after` is useful.

**Comment by atiqsamtia** [comment]
@drbyte Thankyou for your explanation.

I've also a case for both permissions for a role that causes issues.

Gate::after does not alter the result if any permission is already true. there is a mistake in the documentation.
 
https://github.com/laravel/framework/issues/33587

Apparently, Gate::after is only for allowing permission if it is not already allowed. You can't deny permission from Gate::after if it is already granted. (Super Admin scenario only not vice versa)

My main question is, why is Gate::before not being called for all permissions checks and only being called for the permissions which are not granted.

**Comment by drbyte** [comment]
> My main question is, why is Gate::before not being called for all permissions checks and only being called for the permissions which are not granted.

I've not run into a problem with this, so I can't confirm whether that's actually even true. Maybe I've just never been trying to do what you're doing.
Can you create a new example app which does nothing more than recreate this problem without any other dependencies or functionality interfering with it? 
Here's a base starting point: https://spatie.be/docs/laravel-permission/v3/basic-usage/new-app
Then add a seeder with enough permissions, and controller/model/policy/AuthServiceProvider code to recreate the problem ... preferably in separate commits which show different parts being built up to it.
Then share a link to the github repo so I can see the code and run it.

I still think it may be better to redesign your app features to use Model Policies or add some other custom logic into custom permission names (not from this package) as Gate::define permissions that check other criteria along with permissions granted by this package, and then your app can check for those custom defined permissions instead of only checking against permissions that this package manages.
