### ISSUE TITLE
$this-roles is null

### ISSUE THREAD

**Issue by albertatnerdbrain** [spatie/laravel-permission#1589]
I updated to V3 and to laravel 8

After this somehow $this->roles is null, so i tried to use $this->roles()->get(), instead of calling it via magic method and it returned the correct Collection. But to change all these calls manually is not very satsifying to me.

Do you have an idea why this happens?

**Comment by drbyte** [comment]
> $this->roles is null

Every time someone reports this it's because in their model they've added a `roles` property to their model, either as a property in code or as a field they've added to the model's table in the database.

This package declares the `roles` relationship in the trait. If your model declares it as well then the model overrides the trait, resulting in the package not working. This is how PHP works.

**Comment by albertatnerdbrain** [comment]
yes, the problem was as described. Thank you very much
