### ISSUE TITLE
create permissions/roles can be shared with all guards without the need to add them more than one time to the permission/role table ?

### ISSUE THREAD

**Issue by Bassel-kh** [spatie/laravel-permission#1607]
// Create a manager role for users authenticating with the any guard: ( role can be use by any guard )
$role = Role::create(['guard_name' => '*', 'name' => 'manager']);

// Define a `publish articles` permission for the users belonging to the any guard
$permission = Permission::create(['guard_name' => '*', 'name' => 'publish articles']);

I have MULTIPLE GUARDS in my project so I want to avoid duplicate role and permission name in my table.

**Comment by drbyte** [comment]
One way to do that is described here: https://github.com/spatie/laravel-permission/issues/1156

**Comment by DePalmo** [comment]
Didn't want to create new issue, so will borrow this one since it's regarding the same thing.

In linked issue, #1156, in there it was mentioned that future versions will support wildcard guards, even v3 should support it. But the module is already at v4 and their documentation does not mention this in any way.

Is this update still planned? If yes, when can we expect it?

**Comment by adiachenko** [comment]
Personally, I just monkey patched the package to nuke all facilities related to guard management.

Mostly it involved adding this to overriden Role and Permission model but I remember doing some other voodoo to make it work (highly recommend disabling guarded attributes as well to avoid redundant SQL queries):

![image](https://user-images.githubusercontent.com/10194667/111665678-a2196580-881b-11eb-80dc-a22089485ab0.png)
