### ISSUE TITLE
Permission.php does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by RmilaWeb** [spatie/laravel-permission#1611]
After updating composer to version 2 I got this error:

`Class Spatie\Permission\Models\Permission located in ./app/overrides/spatie/Permission.php does not comply with psr-4 autoloading standard. Skipping.`

![image](https://user-images.githubusercontent.com/12487298/98228881-7aef8500-1f59-11eb-9023-b5203bd79265.png)

and in my composer.json file config was:

![image](https://user-images.githubusercontent.com/12487298/98228945-8fcc1880-1f59-11eb-99d8-1ae2729ecfe2.png)

PS: With composer 1 works fine

**Comment by drbyte** [comment]
Why are you using tricky composer substitution rules, when you could just `extend` the model in your own app namespace?

(You are probably getting that message because the namespace and directory don't reflect the directory structure of where you've put that file.)

Use traditional class `extends` method instead.

eg: create `/app/Models/Permission.php`, and instead of `extends Eloquent`, use `extends \Spatie\Models\Permission`
Then build (only) your custom override methods/properties in that class. 
(You don't need to clone the entire original class. Just override the methods/properties you need to change.)

Related docs: https://spatie.be/docs/laravel-permission/v3/advanced-usage/extending#extending

**Comment by RmilaWeb** [comment]
Resolved by adding : 

` "app/overrides/spatie/"`

to the classmap
