### ISSUE TITLE
@role being printed

### ISSUE THREAD

**Issue by robertnicjoo** [spatie/laravel-permission#1621]
I've used this package maybe in 10 of my applications this is the first time I'm seeing such thing.

![544](https://user-images.githubusercontent.com/8672823/99215329-2378d100-2805-11eb-849a-ea763c86b238.png)

and 

![555](https://user-images.githubusercontent.com/8672823/99215365-3f7c7280-2805-11eb-8a43-95821d50fc42.png)

Apparently this issue is not the first time happening:

https://github.com/spatie/laravel-permission/issues/1194

https://github.com/spatie/laravel-permission/issues/1081

https://github.com/spatie/laravel-permission/issues/467

https://github.com/spatie/laravel-permission/issues/1213

https://github.com/spatie/laravel-permission/issues/1290

[And many more](https://github.com/spatie/laravel-permission/issues?page=2&q=is%3Aissue+user%3Arole+issue+in+blade+is%3Aclosed)

Any idea why is this happening?

**Comment by drbyte** [comment]
In every one of those cases the problem was caused by something outside this package. 
Sometimes (many times) it was related another package. Sometimes it was in-app code.
Sometimes it was environment/server issues such as cached views or cached bootstrapping. 
I even saw one with a busted vendors directory that just needed deleting and reinstalling it with `composer install`

Given that the test suite (which tests these directives specifically) is passing on multiple Laravel versions and multiple PHP versions, chances are your situation requires inspecting those same aspects mentioned above.

Fastest way to find it: rebuild your app afresh until you recreate the problem. Then you'll know which step/package/commit is the culprit.
Some people think rebuilding an app's basics is too cumbersome and decide focus on dependencies by removing or downgrading packages. Before you do that, first run `artisan optimize:clear` and delete your `vendors` dir and your `composer.lock` file and run `composer install`. Then test for the problem, to be sure it wasn't environmental or broken cache. Then start tinkering with dependencies.
