### ISSUE TITLE
Error when i try to creat a Role

### ISSUE THREAD

**Issue by zekuraz** [spatie/laravel-permission#1636]
Hey ! When i try to creat a role via tinker, i have this error

```
>>> use Spatie\Permission\Models\Role;
>>> Role::create(['name' => "Super Admin"]);
Illuminate\Database\QueryException with message 'SQLSTATE[23000]: Integrity constraint violation: -407 [IBM][Pilote ODBC System i Access][DB2 for i5/OS]SQL0407 - Valeurs indéfinies non admises dans la colonne ou la variable NAME (SQLExecute[4294966889] at /build/php7.4-YT5f7b/php7.4-7.4.13/ext/pdo_odbc/odbc_stmt.c:259) (SQL: select id from new table (insert into roles (updated_at, created_at) values (2020-12-08 07:42:02, 2020-12-08 07:42:02)))'
```

If somebody have a solution, I thank you in advance.

**Comment by ahmedmamdouh886** [comment]
`insert into roles (updated_at, created_at) values (2020-12-08 07:42:02, 2020-12-08 07:42:02);`

The line above tells you where the issue is, updated_at and created_at are only being inserted, you have to check the mass-assignment.

Check the $fillable array prop in your Role model if it's empty or doesn't have "name" add the 'name' inside the array to be like the following:

protected $fillable = [
'name'
];

and try again.
