### ISSUE TITLE
Model Type

### ISSUE THREAD

**Issue by robertnicjoo** [spatie/laravel-permission#1640]
@drbyte  This is just a request/suggestion

I think the code of this package should be change when role or permission getting assigned to the user, by default it sets `model_type` to `App\User` which is fine till `Larave 7.x` but since `Laravel 8` has changed models directory it should take `App\Models\User` instead.

**Comment by drbyte** [comment]
The model_type is not hard-coded into this package.
It sets the model type based on whatever your model is using.

**Comment by robertnicjoo** [comment]
@drbyte sorry but I don't fully understand it, how come that laravel 8 models are name spacing as `App\Models` and this package somehow assume that models are coming from `App\{model}`? there must be something representing `App\{model}` in this package.

**Comment by drbyte** [comment]
This package uses what Laravel reads as the model_type from the namespace of your model. 

If I install a fresh Laravel 8 application and then install this package, the model_type values stored in the database are `App\Models\User`:
<img width="259" alt="Screen Shot 2020-12-11 at 9 52 07 PM" src="https://user-images.githubusercontent.com/404472/101970899-31025a80-3bfb-11eb-9519-14bd7858a86a.png">

If you have an old Laravel 7 or older app that has old data associated with `App\` instead of `App\Models\` and you have refactored your models into `App\Models\` namespace, then you'll need to update the model_type data in your database records to match the change you're making to your application.

**Comment by robertnicjoo** [comment]
Ok, but I created this app 3 days ago. 
There is a thought however, could it be related to seeders? Cause I seed my roles and permissions as well as users?!
