### ISSUE TITLE
Override Login Eloquent ORM/Query Builder

### ISSUE THREAD

**Issue by jpworx** [spatie/laravel-permission#1643]
Hello,

I have added a column called 'active' into the users table and gave admins permission to set users as active and inactive. Is it possible to override the Eloquent or Query Builder used to Login users? All I need to do is add a WHERE clause to the query so that users cannot sign in if their account is inactive. I'd like to send these inactive users back to the login form with an error message.

I've tried somewhat a hack in LoginController. After the user logs in, I check if active. If not, logout and send error message.  Could someone point me in the right direction as to fixing this hack or editing the query? This is what I have so far

```
protected function redirectTo()
    {
        $this->user = Auth::user();

        if($this->user->active == 1){
            if($this->user->hasRole('driver')){
                return app()->getLocale() . '/somewhere';
            }
            else {
                return app()->getLocale() . '/home';
            }
        }
        else{
            return redirect()->route('login', app()->getLocale())->with('error', 'Your account is currently inactive. Please contact us if this is an error.');
        }
    }
```

**Comment by drbyte** [comment]
Allowing login is an Authentication activity, not an Authorization activity. This package only deals with Authorization.

That said, here are some thoughts for you to explore:

For the actual prevention of login if not `active`, you could use middleware much like the `email verification` feature uses a middleware to check a flag -- it's almost the same as your `active` flag.
One discussion of this is found at:
https://laracasts.com/discuss/channels/laravel/how-to-prevent-a-user-from-logging-in-if-they-have-not-verified-their-email
Additional articles on augmenting the authentication system:
https://medium.com/@mariowhowrites/logging-in-with-laravel-ab700276e1c
https://laraveldaily.com/9-things-you-can-customize-in-laravel-registration/

If you don't want to use middleware for it, you might want to explore overriding Laravel's `authenticated()` method for allowing/denying access based on the `active` flag status because it fires before the `redirectTo()` method you quoted.
https://github.com/laravel/ui/blob/964312989c99db1d5e3b307b833084b81ab58652/auth-backend/AuthenticatesUsers.php#L119-L129
