### ISSUE TITLE
getAllPermissions() has  BUG

### ISSUE THREAD

**Issue by andy236726493** [spatie/laravel-permission#1660]
getAllPermissions() method ,Only returned the inherited permissions, no direct permissions

**Comment by drbyte** [comment]
Seems like the bug is in your application.

This package's test suite [contains a test for this](https://github.com/spatie/laravel-permission/blob/d7aa9192066d356c78b18af07e9b290b223a916e/tests/HasPermissionsTest.php#L372-L384), which is passing.

If there is a bug, please provide a test which demonstrates the bug.
