### ISSUE TITLE
Error when check permission doesn't exists on record

### ISSUE THREAD

**Issue by donnygunawan93** [spatie/laravel-permission#168]
For example I have read,create,update,delete on permissions table.

auth()->user()->hasPermissionTo('create'); // return true or false
auth()->user()->hasPermissionTo('IamNotExists'); // PermissionDoesNotExist in Permission.php line 71:

your hasRole() can return false although the role doesn't exists on roles table,
why not make hasPermissionTo() return similar with hasRole() ?

**Comment by ttomdewit** [comment]
Hi @donnygunawan93,

Looking at the source code and the package's tests, it looks like it's expected behaviour. As soon as it checks for a role by name, it'll throw a `PermissionDoesNotExist` error, as you can see in `Permission.php` starting at line 66:

```php
public static function findByName($name)
{
    $permission = static::where('name', $name)->first();

    if (! $permission) {
        throw new PermissionDoesNotExist();
    }

    return $permission;
}
```

I was trying to come up with a solution that would fit your needs and make a Pull Request, but having given it a little thought, I think the current solution is the correct one, given the fact that what you're looking for simply is not there and it should tell you so.

If `create` is part of your `permissions`, the following code will either return `true` or `false` based on the authenticated user's given permissions.

```php
auth()->user()->hasPermissionTo('create');
```

To me, personally, that makes perfect sense. You know for a fact that `create` is part of your permissions, thus returning `false` means that the authenticated user does not have the aforementioned permission. Returning `true` would mean they do have permission to `create`.

Throwing an exception simply lets you know "Hey, I can't find what you are looking for so it must not exist" meaning it can't return `true` or `false`.

**Comment by donnygunawan93** [comment]
Yes you're right, the current one was good, thx. I miss understanding before.

**Comment by freekmurze** [comment]
@ttomdewit perfect answer 👍

**Comment by cdarken** [comment]
My opinion is that in case the permission doesn't exist the assumption that should be made is that you don't have the permission, because you cannot actually have it assigned.
For everyone that wants to override this behavior, here's how I did it:

import the trait and rename the method
```
use HasRoles {
    hasPermissionTo as traitHasPermissionTo;
}
```

rewrite the method:
```
  public function hasPermissionTo($permission)
  {
        try {
            return $this->traitHasPermissionTo($permission);
        } catch (PermissionDoesNotExist $e) {
            return false;
        }
  }
```
