### ISSUE TITLE
Creating a foreign key

### ISSUE THREAD

**Issue by marchiuzz** [spatie/laravel-permission#1709]
https://github.com/spatie/laravel-permission/blob/b12159e61f94680be0a95ee5b50d9f1099040714/database/migrations/create_permission_tables.php.stub#L45

Would be nice, that if that Model exists, so, migration automatically would add foreign key constraints to model_morph_key

**Comment by drbyte** [comment]
I can see the appeal for that, but it's impossible for the migration to know which models you will eventually assign roles/permissions to, since none exist at the time of running the migration, and the migration doesn't ever run again.

Thus, it is expected that you will assign your own foreign keys (by adding your own additional migrations) if you intend to manipulate the database manually without taking care for those relations.

However, if you use Eloquent commands for removing models then the trait will handle it automatically when deleting roles or permissions:
https://github.com/spatie/laravel-permission/blob/b12159e61f94680be0a95ee5b50d9f1099040714/src/Traits/HasRoles.php#L17-L26
