### ISSUE TITLE
Caching Question

### ISSUE THREAD

**Issue by moisish** [spatie/laravel-permission#1761]
Hello,

From what I can see there is caching on the PermissionRegistrar class which caches all the available permissions and roles on the property $permissions.

What about caching the User's permissions so everytime you use the hasPermissionTo method is not running a query against the DB?

Otherwise why does the cache gets cleared on the methods givePermissionTo, revokePermissions etc if the user's permissions are not cached?

Am I missing something?

**Comment by moisish** [comment]
@freekmurze Any chance you can shed some light?

**Comment by ajuchacko91** [comment]
Hi @moisish,

Your'e correct $permissions property contains all the permissions with roles.

You're wrong that ``` hasPermissionTo``` method is not hitting the db every time. 
On the first call to ```hasPermissionTo ``` creates the cache and uses it on subsequent calls
This is already covered in the ```CacheTest@has_permission_to_should_use_the_cache``` take a look


Note that you could save users permissions on application level though

**Comment by moisish** [comment]
Hi @ajuchacko91,

What I said is that the `hasPermissionTo` is hitting the database every time so any reason why the caching does not cache the user's permissions to avoid hitting the database

**Comment by ajuchacko91** [comment]
Hi @moisish,

I understand what you meant. 
I think package developer avoided caching user's permission is because it will add unnecessary  complications also it makes sense to create a cache per user level(if permissions don't change often) on app which is also easy to manage and still you can avoid hitting db just by checking the cache you created on user level for example:

```
Cache::put("users.{user_id}.roles", 'value');
```
