### ISSUE TITLE
multiple guards unable to share users model

### ISSUE THREAD

**Issue by hihuangwei** [spatie/laravel-permission#1916]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/laravel-permission/issues) or in [the discussions](https://github.com/spatie/laravel-permission/discussions).

**Describe the bug**

````There is no role named `sgcc_nd_grid_worker`.````
this permission guard_name is api，but dashboard guard_name is web. Cannot be use syncRoles function add roles. 

**Versions**
You can use `composer show` to get the version numbers of:
- spatie/laravel-permission package version: 5.3.1
- illuminate/framework package: 8.69.0

PHP version: 8.0

Database version: MySQL 8.0

**Comment by erikn69** [comment]
It is an expected behavior, you can try to do a PR to improve that, just avoid breaking BC
[assigning-permissions-and-roles-to-guard-users](https://spatie.be/docs/laravel-permission/v5/basic-usage/multiple-guards#assigning-permissions-and-roles-to-guard-users)
[the-downside-to-multiple-guards](https://spatie.be/docs/laravel-permission/v5/basic-usage/multiple-guards#the-downside-to-multiple-guards)

**Comment by mcolominas** [comment]
If you are sure that the role or permission exists and that they have the same guard, it is rare that you get that error, but if the database has a guard and you use another to search for that role or permission, it is normal that you get that error.

I have discovered a bug that I just put it right now, this may be your problem #1923

**Comment by freekmurze** [comment]
Fixed in the latest release.
