### ISSUE TITLE
Laravel Policy not working on Role , Permission models 

### ISSUE THREAD

**Issue by fahedtms** [spatie/laravel-permission#2078]
Hi all,

I want to implement Policy inside my app alongside with this package every thing seems to be good unless for the Role and Permission models all the methods return 403 considering that the auth user has all the required permissions.

any ideas why this is happening ?

**Comment by erikn69** [comment]
The guard_name

**Comment by fahedtms** [comment]
sorry could not get you, its all on the web guard

**Comment by fahedtms** [comment]
I searched in all the threads before posting this issue, I could find anything related to it.
I have not use any guards so I don't think I mishandled anything,
as I mentioned all the app on the web guard.

**Comment by erikn69** [comment]
Everything is tested, if you think that there is an issue, make a failing test or a laravel minimal application on fresh installation demonstrating the bug

**Comment by PeanutSquareLLP** [comment]
@erikn69 @fahedtms 
Sure, here's a rewritten version of your comment for a GitHub issue:

---

I faced the same issue, and I fixed it by updating the policy registration. You need to use the role class from **Spatie\Permission\Models\Role** instead of **App\Models\Role**.

Here is the code snippet for the **AppServiceProvider**:

```php
<?php

namespace App\Providers;

use Spatie\Permission\Models\Role;
use App\Policies\RolePolicy;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    protected $policies = [
        Role::class => RolePolicy::class,
    ];

    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        $this->registerPolicies();
    }
}
```

This change ensures that the correct Role class is used in the policy registration.
