### ISSUE TITLE
Checking ownership of a record

### ISSUE THREAD

**Issue by Mysteriosis** [spatie/laravel-permission#222]
I'm pretty confuse on how achieve this.
Let's say we have posts or users tables. It's seems logical that a simple user will have more rights on its own posts (or itself), without a specific role management.

This is an example I found in Laravel doc:
```
Gate::define('update-post', function ($user, $post) {
        return $user->id == $post->user_id;
    });
```
What is the best (generic) way to handle this with your lib ?
Thank you

**Comment by freekmurze** [comment]
You don't need this package to handle that use case. This package is only needed if you need to store additional roles and permission in the database. 

In your case you can just leverage the `user_id` already present on the post. Please review the Laravel docs on authorization to learn more.

https://laravel.com/docs/5.4/authorization

**Comment by omarjebari** [comment]
Would it be possible to reopen this thread?
The issue is that if you mix the use of Spatie Roles/Perms with Laravel Policies/Gates then you are not truly controlling access to a resource solely from the database.
If i were to build an admin system around the perms/roles db then i may have a permission to 'udate_user'.
We will want administrators to be able to update ALL users but we only want a basic user to be able to update their own details.
As far as the db is concerned i have to give the permission to BOTH users (otherwise the policy wont get checked in the case of basic users).
So there is no way to revoke access from the db alone.
The only solutions that i can think of are:
1) Apply unix-style permissions to the entities themselves
2) Add permissions like so: 'update_any_user', 'update_own_user'
In this latter case the policy can check if 'update_any_user' is present and, if not, check if 'update_own_user' is present AND the user owns the record.
The downside of this approach is it increases the number of permissions and makes managing them a little more difficult.
3) Add an 'allow_owner' boolean to the permission record. This can then be used to indicate whether the owner has permission to access the resource and can be checked by the policy. The downside is that a number of db entities may not specifically have an owner. For instance, a book has an author and a publisher, but to 'own' a book record doesn't really make sense.

**Comment by drbyte** [comment]
@omarjebari Thanks for posting. From your post I'm not seeing what this package would need to do.

Generally the best way to handle this sort of thing is to put the list of permissions/roles in the database, and then use policies to control enforcement of access to those abilities. The database-stored names of permissions and roles is simply used to define the relationship between the permissions and the users those permissions authorize.

Then in your app you define all your Gate logic for enforcement, using policies and any other before/after rules.
The policy for a given model would check the combination of both the defined database permissions granted to the current user, plus whatever logic you require for that model, such as ownership or any other relationship that affects authorization to act on it in the manner defined in that policy method.

A very simple example is here:
https://github.com/drbyte/spatie-permissions-demo/commit/fbb35a3589f57453a37c99dab2a265e97e3bb301#diff-9c68eea6979072d7a4ec1ea92efde6f0
You can see here where view/update/delete have app-related code that checks ownership and database-defined permissions to determine what final response is given to the `authorize` command called by the controller.
Note that that commit defined the policy as a resource relationship, but I later updated the example to use individual `authorize` calls for clarity (of what `authorizeResource` does behind-the-scenes) and more granular control: https://github.com/drbyte/spatie-permissions-demo/commit/aa90b3820020b476265a2f215a87f442bec19040

What exactly does this not accommodate for you? 
and if this package were to be changed to accommodate something new, what would that change look like?

**Comment by omarjebari** [comment]
Ok so the issue i have is that looking at the perms in the db is not the universal source of truth regarding whether a user has access to a resource or not. I understand the combined use of policies and db but from the point of view of someone administrating users they can get some unexpected results. For instance, they may give a user access to a resource but the user may still not have access due to a condition in the policy.
The db purely looks at permissions from a user perspective whereas the policy considers both the user and the record in question.

**Comment by drbyte** [comment]
I’m not convinced that the database should have the single source of truth related to every object in your application. Just users. 
Permissions are associated with a user object/model, not with non-user models in your application.

Are you saying that you want a highly complex three directional matrix of permissions persisted in the database in relation to every possible user and non-user model combination in your application?
That seems like it would be both an administrative, coding, and performance nightmare.

Or maybe I am misunderstanding what you were trying to say?

**Comment by omarjebari** [comment]
No that's fair enough, i can see why the authorisation gets split between db and policy now.

**Comment by drbyte** [comment]
Ya, it can be complicated to sort out how best to represent/model all these concepts in an app, and where to draw the line with shoving things into the database, and what degree of granularity needs to be given to the user.
I find often when hitting a block like this it's really screaming [YAGNI](https://jasonmccreary.me/articles/practicing-yagni/) (@jasonmccreary) at me and then I realize I'm over-engineering prematurely. After rethinking I always end up with a simpler and better app. :)

**Comment by omarjebari** [comment]
i appreciate your help on this
