### ISSUE TITLE
RoleDoesNotExist Exception to Log

### ISSUE THREAD

**Issue by yc-public** [spatie/laravel-permission#234]
I want to catch the roledoesnotexist exception and log it into log file. However, i couldn't get the error messages.

My controller : 

```
use Spatie\Permission\Exceptions\RoleDoesNotExist;

public function createAccount() {
		try {
				$user = User::create([
				'email' => 'super@abc.com',
				'password' => bcrypt("abc"),
				]);
				
				$user->assignRole('super!admin');
			} catch (RoleDoesNotExist $e) {
			Log::error('Register Failed: ' . $e->getMessage(), $this->_logRoute);
			return $this->responseFailed();*/
		} catch (\Exception $e) {
			Log::error('Register Failed: ' . $e->getMessage(), $this->_logRoute);
			//return $this->responseFailed();
		}
}
```

My Log:

2017-03-22 16:32:04 local (ERROR) ["SuperAdminController@createAccount",19] --- Register Failed: 

which is showing nothing about the exception message.

**Comment by AlexVanderbist** [comment]
Hi @yc-public 

This is because the `RoleDoesNotExist` exception is thrown without a message. That's why `$e->getMessage()` doesn't log anything.

I suggest you just log the entire `$e` exception instance. This way the [`__toString()`](http://php.net/manual/en/exception.tostring.php) magic method will kick in and print some useful information:

```php
try {
     //
} catch (RoleDoesNotExist $e) {
    Log::error('Register Failed: ' . $e, $this->_logRoute);
}
```
