### ISSUE TITLE
404 takes precedence over 403

### ISSUE THREAD

**Issue by tarraq** [spatie/laravel-permission#2371]
**Describe the bug**
I have an application where I have regular users with no roles and admins and employees with corresponding roles. 
I am wrapping admin-area in the role middleware, which works well.
However, when I ask for a resource in that area, that returns 404 for the logged in admin and employee users, it also returns 404 for the logged in normal user. Would expect it to return 403, to not give away any details about what exists and what doesn't. 

**Versions**
"spatie/laravel-permission": "^5.9",
"laravel/framework": "^10.0",

PHP version:
8.2

**To Reproduce**
Wrap a resource controller in role middleware. Access an unknown entity

**Expected behavior**
Expecting HTTP 403 instead of 404

 **Additional context**
I use the automatic model injection from routes to controllers.
I suspect this is the culprit in this.

**Comment by tarraq** [comment]
This is the order in routes. 

`Route::middleware('auth')->group(function () {
    Route::group(['middleware' => ['role:admin|employee']], function () {
        Route::prefix('admin')->group(function () {
            Route::get('/', [HomeController::class, 'index'])->name('Admin.home');`

**Comment by drbyte** [comment]
What's happening is by design: that's how Laravel works when you nest your defined routes inside the permission middleware: since the middleware fails for the unauthorized user, the route names don't "exist", thus 404.

You could try removing the `(['middleware'....role:admin|employee']...)`check from your routes file and put the middleware in your Controller instead. Then when the controller runs for the unauthorized user it will return a 403 instead.
