### ISSUE TITLE
Migration from v1 to v2?

### ISSUE THREAD

**Issue by drbyte** [spatie/laravel-permission#262]
I'm aware that v2.0.0 was only tagged a few hours ago.

In studying the code changes, I note that the schema is significantly different, but no migration script has been provided (as far as I can tell).

Naturally people won't want to lose any data when upgrading; is there a recommended migration approach?  (I note that renaming config file and db tables isn't suitable, due to schema changes and config file contents).

In the meantime of course one can force use of v1 by ensuring `composer.json` specifies a `^1` version:

```json
    "require": {
...
        "spatie/laravel-permission": "^1.3",
...
```

**Comment by freekmurze** [comment]
Although it's certainly technically possible I'm not planning on upgrading from `v1` to `v2` in any of my projects. That's why I didn't write a migration script or notes on how to achieve it.

I'm thinking the best way to approach this would be to completely uninstall `v1` (but keep your `permissions` and `roles` tables somewhere safe) and install `v2` from scratch. The values from the old `permissions` and `roles` tables must that be imported into the new tables. The structure is somewhat the same. The most important addition is the added `guard_name` column. In mos cases you should set this to the name of your default guard.

I surely accept a PR to the readme that explains how to migrate from `v1` to `v2`.

**Comment by fabricecw** [comment]
Check #771 for migration script.
