### ISSUE TITLE
Laravel 11 compatibility issues

### ISSUE THREAD

**Issue by AsjidAle** [spatie/laravel-permission#2645]
**Docx Fixes:** Due to the new release of the Laravel framework, the directory structure has become updated but this is compatible with the old version of Laravel 11, there are being couple of issues stopping it from working:

In Laravel 11, the service providers are auto-registered as the new service providers extend the ServiceProvider class that registers automatically but Laravel-permissions are not working due to this in Laravel 11.

As well as no, more traditional old need to register in config/app.php.

**Comment by jord3v** [comment]
in app.php use 

->withProviders([
  // Add providers here....
])

**Comment by AsjidAle** [comment]
Thank! I knew that the solution but there's need to be update in docx.

**Comment by jord3v** [comment]
It's already in the documentation, as follows:

https://spatie.be/docs/laravel-permission/v6/basic-usage/middleware

**Comment by drbyte** [comment]
I don't understand how you're having any problem with it as-is.

Since the beginning, in all prior Laravel versions, adding this package to `config/app.php` was always optional due to self-registration. And it still auto-registers itself because it extends Laravel's `ServiceProvider` class.
https://github.com/spatie/laravel-permission/blob/8ed61aa42031f3cf06b5f68569af5e2e1e481284/src/PermissionServiceProvider.php#L12-L17

If you want to register it manually, you can, but it is not necessary.

**Comment by AsjidAle** [comment]
Thanks for the your valuable time, I got it, the misunderstanding occur due to laravel 11 update in directory structure.

**Comment by robertnicjoo** [comment]
Put it in `bootstrap\providers.php`

```php
<?php

return [
    App\Providers\AppServiceProvider::class,
    Spatie\Permission\PermissionServiceProvider::class,
];
```
