### ISSUE TITLE
Can this be extended to only use single role?

### ISSUE THREAD

**Issue by rodwin** [spatie/laravel-permission#277]

**Comment by freekmurze** [comment]
Could you elaborate on that question? Eventually submit some code examples on what you're trying to achieve?

**Comment by mlab817** [comment]
i know that this issue is closed but for those like me who wanted to achieve this.

What i deed is to create another table to store all roles assigned to user (`assigned_roles`) which is basically similar to `role_user` table provided by the package. The purpose of this is to allow users to toggle between their assigned roles.

Then, basically, i sync only a single role every time to capture the user toggling between their assigned roles.

Why the hassle? The package collects all permissions from roles assigned to the user so you need to limit the role to one in the package `role_user` table.

Ideas are welcome.

Hope this helps.
