### ISSUE TITLE
`There is no permission named ... for guard web` keeps recurring

### ISSUE THREAD

**Issue by bilogic** [spatie/laravel-permission#2774]
### Description

I was able to fix it for one of my projects, but this one is persistent. No amount of cache clearing helped. 
I already ran `app(PermissionRegistrar::class)->forgetCachedPermissions();` after seeding.

Any ideas?

```
$ art tinker
Psy Shell v0.12.7 (PHP 8.2.26 — cli) by Justin Hileman
> \Spatie\Permission\Models\Permission::findByName("view_any_checkoutLog", "web")

   Spatie\Permission\Exceptions\PermissionDoesNotExist  There is no permission named `view_any_checkoutLog` for guard `web`.

> \Spatie\Permission\Models\Permission::find(86)
= Spatie\Permission\Models\Permission {#9438
    id: 86,
    name: "view_any_checkoutLog",
    group: "Checkout Logs",
    description: null,
    guard_name: "web",
    created_at: "2024-12-11 00:07:17",
    updated_at: "2024-12-11 00:07:17",
  }

> 
```

### Steps To Reproduce

See description

### Version of spatie/laravel-permission package:

5.11.1

### Version of laravel/framework package:

10.48.25

### PHP version:

8.2.26

### Database engine and version:

MySQL: 8.0.37

### OS: Windows/Mac/Linux version:

Ubuntu 22.04.5 LTS

**Comment by drbyte** [comment]
- How was the Permission record initially created? (ie: did you use a function call from this package's API? or did you inject it manually into the database some other way?)
- When was it inserted? (ie: application code, vs migration, vs seeder)
- Can you share the code for that?
- You've changed the default migrations by adding your own additional fields. Can you share more details about that?
- Have you also changed additional Model properties to accommodate those additional fields?
- Your `tinker` example shows you referring to this package's core Models, but your custom fields imply that you're probably (or should be) using models extended into your own App.
- Does changing the package cache `expiration_time` to `0` (only temporarily as a test) make any difference in the results?
- Does calling `findOrCreate()` instead of `findByName()` trigger an expected "already exists" error? If yes then it would seem like a cache issue; If no, then it would suggest something in your application code is conflicting with how the PermissionRegistrar finds and retrieves records (including caching, but not primarily related to Laravel's cache).

**Comment by bilogic** [comment]
@drbyte thanks for getting back, yes the description field was the only additional field added, but as you can see, I'm using the same model, to illustrate how illogical the issue seemed to me.

I'm trying to fix a private package that provides laravel-permission to several projects, and after the OP, I found several mistakes that were eventually recitified. I think the one in question had some cache clearing issues.

I will take note of `expiration_time`, perhaps a default of `0` when the `APP_DEBUG = true` will help lessen these support issues.

Thank you!
