### ISSUE TITLE
how to use role permissions in blade

### ISSUE THREAD

**Issue by jespersgaard** [spatie/laravel-permission#279]
Hello
first thank you for a great packages, currently trying to implement it.

when i assign a user to a role and give that role a permission, can i use that permission in blade with the @can function?
it doesn't seem to do the trick, and i have to assign the permission to the user before it works.

what do i need to include in the User model for this to work?
currently i have includede:

```
//User.php Model

use Spatie\Permission\Traits\HasRoles;
use HasRoles;
```

regards Martin

**Comment by sebastiandedeyne** [comment]
The `HasRoles` trait should be enough. Could you clear your cache after assigning the permission to the role and try again?

**Comment by jespersgaard** [comment]
thank you that did the trick.
but do i have to clear the cache every time i create new roles and permissions and assign these to a user/role?

**Comment by jespersgaard** [comment]
and now that I am here, is there a way to auto assign a permission to a role each time a new permission is created?

thank you for your help :-)

**Comment by sebastiandedeyne** [comment]
> but do i have to clear the cache every time i create new roles and permissions and assign these to a user/role

You need to clear the cache every time you assign a permission to a role.

> and now that I am here, is there a way to auto assign a permission to a role each time a new permission is created

This really depends on what your needs are. For things like this, I'd recommend looking in to model events and Eloquent observers: https://laravel.com/docs/5.4/eloquent#events

**Comment by drbyte** [comment]
> You need to clear the cache every time you assign a permission to a role.

@sebastiandedeyne Since the package is used to assign permissions to roles, shouldn't the package take care of updating the cache automatically?

**Comment by sebastiandedeyne** [comment]
Interesting question. Since it's via the database, nothing's stopping users from using plain relationship methods or queries to assign permissions to roles. In that case, a cache clear would need to happen manually.

I'd rather say that users always need to ensure the cache is cleared, than sometimes.

Also, I think the default cache driver is used often, so sometimes flushing the cache would flush way more than just the permissions. I don't want our package to have such an invisible impact on an application.

**Comment by drbyte** [comment]
I agree that we can't stop users from manually manipulating the database themselves, and in such cases they must clear the cache themselves too, specifically `spatie.permission.cache`

I just browsed through the package's source again, and see that it does indeed clear the cache when the package's methods are used to assign/revoke permissions/roles. This is what I thought you were saying was *not* happening, in your prior post.

Caching is great, but it's been the most common problem subject in this package's "issues" since caching was introduced to it.  And the readme makes no mention of caching or which cache tag to clear, etc. That might be a worthwhile addition, perhaps for a "troubleshooting", or "not seeing your changes?" section?

**Comment by sebastiandedeyne** [comment]
> This is what I thought you were saying was not happening, in your prior post.

Whoops 😅  Didn't write this package so misinformed myself there

It's true though that this seems to be a reoccurring issue, what do you thing @freekmurze, a note in the readme?

**Comment by freekmurze** [comment]
@sebastiandedeyne yea, it was introduced fairly recently by @AlexVanderbist 

I'd accept a PR that adds a troubleshooting section to the readme.
