### ISSUE TITLE
Decoupling Eloquent

### ISSUE THREAD

**Issue by CupCoffee** [spatie/laravel-permission#308]
Hi,

We've had a request from our client which requires us to re-implement our user logic by using a 3rd party API. For our roles and permission we use your package.

I was wondering if there was an easy way to switch the Eloquent datalayer with an API. I am curious to your recommendations on this matter :).

Btw, i just noticed your postcard policy. We've been using your package in production for over a year now and have yet to send a postcard! I'll look into sending it ASAP!

**Comment by sebastiandedeyne** [comment]
Hi @CupCoffee,

We're probably not going to decouple this package from Eloquent, because it would add a *lot* of complexity, and Eloquent is definitely good enough for the 90% use-case.

Not sure what I can say to help you out, since it all depends on how the API is set up. I think some calls in this package need to do a few database queries to determine the permission, if that'd be translated to HTTP requests, you'd have a really slow application.

Maybe you could write a sync to map API contents to your database, and keep using this package? That way you'd be able to keep using this package, and you'll most likely need to keep the data cached locally anyway, two birds with one stone :)
