### ISSUE TITLE
[Feature] Add  hasPermissionTo to Roles model

### ISSUE THREAD

**Issue by mgambati** [spatie/laravel-permission#31]
It will be very useful when dealing with many roles and permissions.

I would write it, but my testing skills is not good enough to make a PR.

**Comment by freekmurze** [comment]
My thinking is that you it's better to check the permissions of a user, instead of checking the permissions of a role. 

The only time you might want to retrieve the permissions is when builiding a screen to administer the permissions of a role. But then you could just loop through the permission relation on role.

**Comment by jpmurray** [comment]
@freekmurze : just curious, what makes looping through it more of a better option then `$role->permissions()->sync($array_for_permissions_id);` ?

**Comment by freekmurze** [comment]
If you want to save using `sync` is indeed the best option. In the example above I was thinking about rendering a list.
