### ISSUE TITLE
Using trait with non-user model

### ISSUE THREAD

**Issue by FourStacks** [spatie/laravel-permission#310]
First up thanks so much for all the work on this package (and all the other Spatie packages)!

This isn't a bug per-se, more of a question relating to guards.  I'm building a multi tenant SPA and the model that I want to give roles to isn't one that is authenticated:

I have a User model with the standard email/password fields but as a User can belong to many Accounts, in my app each user has a one-to-many relationship with an AccountProfile model.

A User can have different roles for each account they are a member of so I'm saving the Role on the AccountProfile model.

I've got things working but only if I explicitly save my Role models with `guard_name` set to ''.  If I don't do this then I get errors such as 

    The given role or permission should use guard '' instead of 'web'.

This makes sense to me as there is obviously no auth guard associated with a non-auth model like the one described above.

I'm happy enough to set the the guard_name like this but I just want to check I'm not storing up trouble for myself down the line?  I would guess that I'll be unable to use the multiple guards feature of the package but for the forseeable future I don't think this will be an issue.

**Comment by freekmurze** [comment]
> This makes sense to me as there is obviously no auth guard associated with a non-auth model like the one described above.

Sounds logical to mee too.

> I'm happy enough to set the the guard_name like this but I just want to check I'm not storing up trouble for myself down the line? I would guess that I'll be unable to use the multiple guards feature of the package but for the forseeable future I don't think this will be an issue.

If you aren't planning on using multiple guards, you'll be fine.

**Comment by FourStacks** [comment]
@freekmurze Awesome, thanks for the response Freek (postcard will be forthcoming!)

**Comment by sebj54** [comment]
Just posting here so others facing the same issue can find another solution. I tried to specify the `guard_name` when creating roles and permissions but it didn't work. I even a weird error at some point: `The given role or permission should use guard `` instead of ``.`

For the example, let's say we have a `User` model which can have several `Profile` models linked. Between those two tables, there is a `ProfileUser` pivot table and we add roles to this pivot table.

The only thing needed is to add a `guardName` method to the `ProfileUser` pivot model (in my case, I stick to the default guard):

```
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Relations\Pivot;
use Spatie\Permission\Traits\HasRoles;

class ProfileUser extends Pivot
{
    use HasRoles;

    public function guardName()
    {
        return config('auth.defaults.guard');
    }
}
```
