### ISSUE TITLE
Permissions not registered with gate during tests

### ISSUE THREAD

**Issue by timothyvictor** [spatie/laravel-permission#457]
Hello. I must be doing something wrong, but my http tests are failing on routes protected by the auth guard. 

I'm using laravel 5.5 and laravel-permission 2.5.3

In my db migrations I have the following:
```php
        $manageTeachers = Permission::create(['name' => 'manage teachers']);
        $manageLessons = Permission::create(['name' => 'manage lessons']);
        $manageStudents = Permission::create(['name' => 'manage students']);
        $viewAdminPanel = Permission::create(['name' => 'view admin panel']);

        $teacherRole = Role::create(['name' => 'teacher']);
        $adminRole = Role::create(['name' => 'admin']);

        $teacherRole->givePermissionTo('run lessons');
        $adminRole->givePermissionTo(['manage teachers', 'manage lessons', 'manage students', 'view admin panel']);
```

and in my routes/web.php I have this:
```php
Route::group([
    'prefix' => 'admin', 
    'namespace' => 'Admin', 
    'as' => 'admin.',
    'middleware' => 'can:view admin panel',
  ], function () {
       // some routes
});
```
This all works as expected in the browser, but not in my tests - when I test the routes I'm getting `Illuminate\Auth\Access\AuthorizationException: This action is unauthorized.`
The tests are like:
```php
$admin = $this->createAdmin();
$response = $this->actingAs($admin)->get(route('admin.import.lesson.index'));
// a bunch of assertions
```

Finally in my testCase.php, I set up the admin like this:
```php
    private function createUser($firstName = 'The', $surname = 'User')
    {
        $person = factory(Person::class)->create([
            'first_name' => $firstName,
            'surname' => $surname,
        ]);
        $user = factory(User::class)->make();
        $person->user()->save($user);
        return $person->user;
    }
    protected function createAdmin(){
        $user = $this->createUser();
        $user->assignRole('admin');
        return $user;
    }
```

Interestingly, when I add debugging, the createAdmin() function returns:
```php
    protected function createAdmin(){
        $user = $this->createUser();
        $user->assignRole('admin');
        dump($user->hasPermissionTo('view admin panel')); // true
        exit(dump($user->can('view admin panel'))); // false
        return $user;
    }
```
So, it seems like the permissions are not being registered with the gate, 

I'm sure this is an issue with me rather than the package, so any pointers would be gratefully received. 

Tim

**Comment by uxweb** [comment]
I have the same issue when running my tests.

**Comment by uxweb** [comment]
Hi!

I just discovered that this issue is related to the time that the `PermissionRegistrar` is being called when running tests. I still don't know why the database migrations run after the registrar is called.

I was able to solve this issue by adding this line to the setUp method in my tests:

```
    public function setUp()
    {
        parent::setUp();

        $this->app->make(PermissionRegistrar::class)->registerPermissions();
    }
```

Hope this is useful while the issue is solved.

**Comment by freekmurze** [comment]
I've just tagged `v2.5.4`. Does that version solve your issue?

**Comment by uxweb** [comment]
@freekmurze 

I just upgrated to `v2.5.4` but the issue is still happening.

I upgraded to Laravel 5.5 a few hours ago. I guess it has something to do on how migrations are running. I think that migrations are running within a transaction that has isolation from reads, and I guess that's why maybe the registrar is not able to add the permissions to the Gate. I still don't have evidence to prove it, this is just my guess.

I'll be investigating more.

Thanks

**Comment by timothyvictor** [comment]
Hello @freekmurze - still getting the same issue with v2.5.4

Thanks @uxweb that certainly does solve the issue in the meantime. 

I'll have a root around myself and see if I can spot anything useful.

**Comment by drbyte** [comment]
I set up a demo application with 2.5.3 in order to test this issue. 

While the app is basic, and so are the tests, the granting of roles and then subsequent testing of roles and permissions using both `hasPermissionTo` and `can` are working properly:

https://github.com/drbyte/spatie-permissions-demo/blob/master/tests/Unit/RolePermissionGrantTest.php

**Comment by uxweb** [comment]
@drbyte 

For the record, I'm using sqlite :memory: database when running the tests.

You are using a file database with permissions and roles already seeded.

The registrar is trying to register permissions in the gate before the permissions are actually inserted in the database.

I think it has to do with the order that service providers are being called?.

Thanks!

**Comment by drbyte** [comment]
@uxweb You are correct: Laravel boots the `PermissionServiceProvider` before the tests are run. Thus there are no permissions in the database (file or memory, whatever) for it to register.

It appears that you will need to fire `registerPermissions()` after any creating-on-the-fly of roles and permissions you are doing in your tests.

Actually, in this package's tests, it both clears the cache and re-registers the permissions: https://github.com/spatie/laravel-permission/blob/master/tests/TestCase.php#L128-L130 after creating the base permissions in the database at https://github.com/spatie/laravel-permission/blob/master/tests/TestCase.php#L37-L39
