### ISSUE TITLE
Symfony \ Component \ HttpKernel \ Exception \ HttpException No message

### ISSUE THREAD

**Issue by BAKTETE** [spatie/laravel-permission#466]
the package is working just fine but after a few days the `routes` that uses the `Middleware` of the package become inaccessible and the following errors triggers from no where 

For example all `controllers` that uses this `__construct()`  like `UserController`
```
public function __construct() {
        $this->middleware(['auth', 'permission:Administer roles & permissions']); //Permission middleware lets only users with a //specific permission permission to access these resources
    }
```
throw this error
![whoops there was an error](https://user-images.githubusercontent.com/27772375/30608424-345cd4da-9d70-11e7-8052-12df5a8a4f52.png)
![whoops there was an error 2](https://user-images.githubusercontent.com/27772375/30608428-3958bb3e-9d70-11e7-8579-5c01b6a87f92.png)

and `controllers` that uses the following  `__construct()`
```
public function __construct()
     {
        $this->middleware(['auth', 'clearance']);
     }
```
the `ClearanceMiddleware` contains
```
if ($request->is('mail/create'))//If user is creating a post
        {
            if (!Auth::user()->hasPermissionTo('Create Post'))
            {
                abort('401');
            } 
         else {
                return $next($request);
            }
        }
```
throw this error
![whoops there was an error 3](https://user-images.githubusercontent.com/27772375/30609411-437474ca-9d73-11e7-837c-32f203abc794.png)
![whoops there was an error 4](https://user-images.githubusercontent.com/27772375/30609424-48f3aa2e-9d73-11e7-93dd-52847d4cc699.png)
![whoops there was an error 5](https://user-images.githubusercontent.com/27772375/30609434-4ed3ee54-9d73-11e7-887f-08ba21246979.png)
![whoops there was an error 6](https://user-images.githubusercontent.com/27772375/30609442-52d3d3b6-9d73-11e7-9391-21fb06642035.png)
![whoops there was an error 8](https://user-images.githubusercontent.com/27772375/30609450-580d06a4-9d73-11e7-81f8-5fa871a79cc1.png)
![whoops there was an error 9](https://user-images.githubusercontent.com/27772375/30609457-5bd74e8e-9d73-11e7-821a-32f89d67ea81.png)

when i run the following commands the package start working like nothing happens
`php artisan config:cache` `php artisan cache:clear` `php artisan view:clear` `php artisan route:clear`

**Comment by drbyte** [comment]
What caching engine are you using? Is it overloaded with too much content, or is it failing in some way that causes no data to be returned?

**Comment by drbyte** [comment]
1. That depends also on what your `.env` file has set for CACHE_DRIVER.
Judging from your other screenshot error messages it's probably also set to `file` there.

2. Your screenshots are showing a server filesystem error indicating that you don't have `write` permissions to store cached data.
So, it would seem the issue is that your server is either running out of allowed disk space (caused by logs, caches, view-caching, and more) and thus is not able to properly update the cache, which could in turn cause the cache to not be readable reliably ... which in turn will cause this package to not return `true` for configured permissions, because the lookup for permissions is failing due to cache errors.

So, it would seem this package is merely exposing a separate problem you have, and this package is in itself not the actual problem.

I recommend taking these concerns to your Ops team for investigation. 

One alternative could be to switch your cache layer to use redis or mysql. But you'll still need to resolve your filesystem permissions errors, as those could be causing other (somewhat silent, but fatal) problems in your system.

**Comment by BAKTETE** [comment]
@drbyte 
**thank you** for your rich informations i will take this to my team but i'm sure the solution is within your post

**Comment by jesswenn** [comment]
I had the same problem with No message error. I went to finder and my project folder. 
Right click for show info. 
Then you put your writing privileges in competence to read and rights to everyone on permissions. It worked for me i get no error no message anymore.
