### ISSUE TITLE
Use another DB connection for User, Roles and Permissions

### ISSUE THREAD

**Issue by matbeard** [spatie/laravel-permission#481]
I need to access the users, roles and permissions from a separate Laravel app which uses a different database.

I've created the appropriate database connection and used this in my User model and custom Role and Permission models (which are specified in the permission config file).

However, although Users are able to authenticate, none of their registered roles are working. When I try:
`User::role('role name')->get()` it returns an error: `RoleDoesNotExist` even though it does exist and the same command works in the other Laravel app.

Any advice on how to use a different connection for the Role and Permission models?

Thanks

**Comment by AlexVanderbist** [comment]
At first thought this is due to the internal caching of roles and permissions. This cache isn't cleared when changing permissions and roles in the database directly (and thus remains empty in your case as no roles/permissions have been created in your separate app). 

I'd suggest lowering the `cache_expiration_time` config in your separate Laravel app, maybe even completely disabling it. We're looking for a better solution for this issue in v3 of the package.

**Comment by matbeard** [comment]
I thought it could be something to do with that, but I've manually cleared the cache on both applications (just to be sure), and it's not fixed the issue (I've also tried your above suggestion).

The thing is, it's working in the other Laravel app which also uses my own Role and Permission models. So it must be reading the correct models from the config file.

I thought it could be something to do with the relationship models, but surely if it was using the wrong connection for these it would throws a different error?

**Comment by AlexVanderbist** [comment]
It looks like you're right. Even though the right connection is set for the `User` model, the default connection is still used for `Permission` and `Role` models. I'd suggest extending those two classes and adding the `$connection` property. Don't forget to change your `permission.php` config to use the new classes as well.
