### ISSUE TITLE
How to secure laravel-permission modules, file-manager or settings?

### ISSUE THREAD

**Issue by Stahoo** [spatie/laravel-permission#507]
Hello

I created two roles: admin and editor. I can secure the menus of these modules directly into the resources/views/vendor/backpack/base/inc/sidebar.blade.php using
```blade
                @role('admin')
                <li class="header">{{ trans('backpack::base.administration') }}</li>
                <!-- ================================================ -->
                <!-- ==== Recommended place for admin menu items ==== -->
                <!-- ================================================ -->
                <li><a href="{{ url(config('backpack.base.route_prefix', 'admin') . '/dashboard') }}"><i class="fa fa-dashboard"></i> <span>{{ trans('backpack::base.dashboard') }}</span></a></li>
                <li><a href="{{ url(config('backpack.base.route_prefix', 'admin') . '/elfinder') }}"><i class="fa fa-files-o"></i> <span>File manager</span></a></li>
                <li><a href="{{ url(config('backpack.base.route_prefix', 'admin') . '/backup') }}"><i class="fa fa-hdd-o"></i> <span>Backups</span></a></li>
                <li><a href="{{ url(config('backpack.base.route_prefix', 'admin') . '/log') }}"><i class="fa fa-terminal"></i> <span>Logs</span></a></li>
                <li><a href="{{ url(config('backpack.base.route_prefix', 'admin') . '/setting') }}"><i class="fa fa-cog"></i> <span>Settings</span></a></li>
                <!-- ======================================= -->
                <li class="header">{{ trans('backpack::base.user') }}</li>
                <!-- Users, Roles Permissions -->
                <li class="treeview">
                    <a href="#"><i class="fa fa-group"></i> <span>Users, Roles, Permissions</span> <i class="fa fa-angle-left pull-right"></i></a>
                    <ul class="treeview-menu">
                        <li><a href="{{ url(config('backpack.base.route_prefix', 'admin') . '/user') }}"><i class="fa fa-user"></i> <span>Users</span></a></li>
                        <li><a href="{{ url(config('backpack.base.route_prefix', 'admin') . '/role') }}"><i class="fa fa-group"></i> <span>Roles</span></a></li>
                        <li><a href="{{ url(config('backpack.base.route_prefix', 'admin') . '/permission') }}"><i class="fa fa-key"></i> <span>Permissions</span></a></li>
                    </ul>
                </li>
                @endrole
                <li><a href="{{ url(config('backpack.base.route_prefix', 'admin') . '/logout') }}"><i class="fa fa-sign-out"></i> <span>{{ trans('backpack::base.logout') }}</span></a></li>
            </ul>
```
Of course, this is not the end, as you still have to secure access to the module for the editor by entering the URL. in vendor/backpack/permissionmanager/src/app/Http/Controllers/PermissionCrudController.php method setup can use 
`Auth::user()->hasRole('admin')`
and throw error or redirect but ... 

This is not a good solution (writing in modules in vendor). What should I do? How to secure editor access to the mentioned modules. Sorry if it's too easy for you, I'm just starting to have fun with Laravel

**Comment by drbyte** [comment]
You raised 2 questions:
1. Should you edit the sidebar view directly? 
Answer: yes. That is code you control yourself. (But, like any views which are obtained by publishing assets from a vendor package, be aware that if you re-publish their assets in your project you might accidentally wipe out your customizations.)

2. Should you edit the `PermissionCrudController.php` directly? 
You are correct that "best practice" is to not edit vendor package code directly. 
But this question (how to bring role/permission control into the controller) is really something you should ask the Laravel Backpack team, since it's their package you're asking about. 
(Backpack is imply leveraging the role/permission capabilities from this spatie package; but how you implement more of the spatie package's features inside Backpack is a Backpack-specific question.)

Does that help?

**Comment by Stahoo** [comment]
thank you very much. You have confirmed me that it is not implemented (I think it should be obvious;)). Now :). I will write to the authors. For now, I extends CrudController the role checking with big note TODO. When I get an answer I will share it here. Thank you again

**Comment by AlexVanderbist** [comment]
Hey @Stahoo, 

>What should I do? How to secure editor access to the mentioned modules.

Instead of checking for the `admin` role in the `PermissionCrudController` directly you can also check for the `admin` role in the route middleware. 

Somewhere in your Laravel Backpack project you'll have the `permissionmanager.php` routes file: 
https://github.com/Laravel-Backpack/PermissionManager/blob/1f922c539ebb71b11173b872114ad355690de4a6/src/routes/backpack/permissionmanager.php

In the group middleware you can define a third `role:admin` middleware which will check if the user accessing one of the permission routes has a given role (in this case `admin`): 
```
        'middleware' => ['web', 'admin', 'role:admin'],
```

Good luck!

**Comment by Stahoo** [comment]
@AlexVanderbist 
I try this solution, but i have problems. I try this today again.
Thx
