### ISSUE TITLE
Adding morph fields?

### ISSUE THREAD

**Issue by llhilton** [spatie/laravel-permission#576]
I'm interested in using this package, and I'm wondering how hard it might or if anybody has experience with adding some morphs to it. For example, a user might have several roles and need to have different access depending on their role and location. Say a user is a store manager at one location. They need to be able to make sales, see all that's store's inventory and make shipments and all that good stuff. But at another location, they just help out as a regular employee, so they should be able to make sales, but not see the inventory and the like. 

I've done something like this manually, where the role has a morph, and the morph fields are whatever location or other model that the user's role is assigned to. I didn't really need to get super granular with the permissions on that one, so I ended up mostly just doing my auth check with roles, but my next project has more needs, which generally this package satisfies, except for the morph type thing. Would appreciate any thoughts or experience folks have on whether I could extend this package to handle this. (Or maybe a tap on the shoulder and a point in a better direction to handle this sort of situation!) :)

**Comment by drbyte** [comment]
Hi! Can you explain a bit of detail about how you differentiate between "locations" in this sort of scenario? How "multi-tenant" is this setup? 

And,... if you were to temporarily envision this scenario as one where this "user" were two different users in your system, and those two different users had the necessary roles/permissions to do exactly as you described, .... then what factors would have to be "merged" in order to allow these separations to operate for just the single user, so they only require a single login instead of multiple separate accounts?

(I imagine you've already thought of most of these, but if you can share some more of those details, it may help us reply with a solution even more relevant to your situation/context.)

**Comment by hrabbit** [comment]
I might be missing the overall point here but I think what you are asking for is effectively an extra field attached to the role or permission (or maybe even model_has_roles, model_has_permissions or role_has_permissions) tables in order to define a different "location" for each role (or permission). I think you could do that easily just by creating a new role, permission, model_has_roles, model_has_permissions or role_has_permissions table model and extending the current one (Remember to update the config). Afterwards, add your morph details (relationships) to this model.

As an example, I do something similar but apply a "Flags" table to the roles and permission models in order to add miscellaneous information. (In this case, it's used for a friendly description).

Below is an "untested" snippet from a morph that connects to my Roles (It's actually a trait in my system so can be applied to anything) but I've extracted it directly into the model for visual ease.
```
<?php

namespace App\Models;

class Role extends \Spatie\Permission\Models\Role
{
    public static function boot()
    {
        static::addGlobalScope('Location', function ($builder) {
            $builder->with('Location');
        });
    }

    public function Location()
    {
        return $this->morphMany('App\Models\Location', 'location');
    }
}
```

PS. I know I could use more "use" options here but I like to see the full namespaces. (Personal preference).

Apologise if that is way off the mark from what you are trying to produce.

**Comment by llhilton** [comment]
@hrabbit, that's along the lines of what I was thinking. I haven't done any customizing of packages in this way, so I wasn't sure if it was possible or how to go about it. (Always something new to learn!) :) I'm actually thinking of doing this in a couple of different applications. One would be a rework of stuff I've done before, but another would be a new use (whose requirements are less explicitly stated than I might like!) 

Thanks for your help!

**Comment by llhilton** [comment]
So for the traits, I could make a trait that uses the package traits and just over-write any of the functions I need to?

**Comment by hrabbit** [comment]
@llhilton, I'm not sure you can over-write a method from within a trait as the trait itself is treated as part of the calling class directly. (This can cause naming conflicts)

As for your situation, I was thinking a little further on it, and if you wanted to have a particular role specific to a particular location, you could probably create a new migration that adds the extra location_id column to the model_has_roles table (That would allow any model to have a location), then create your own model_has_roles class that extends the Spatie model_has_roles model and include the relationship itself. 

Side effects of this are that every model in the roles table has a location, even if you didn't want it to. Again, not sure if that affects your situation or not.

But as @drbyte mentioned, without very clear understandings of how your locations <> roles work, we would be stumbling around in the dark.

**Comment by llhilton** [comment]
So, this is the migration I would need to do what I want
https://pastebin.com/Pae9puVs

A role or permission might have a class that it would be restricted to. Then, the model_has_role and model_has_permission would need to be "restricted" to an instance of that class via the "restrict_to" morphs. 

To implement this, though, most of the functions that would need to be updated appear to be in the HasRole trait, where I'd need to check not only the permission itself but also the restrict_to morphs. 

For example, we might have a role of admin that has the restrict_to_class of "App\Models\Project." Then, when a user is assigned that role, an instance of the Project class has to be assigned as well. So then, that user might be an admin for project "divers" but not for project "scaffolding." So when checking if the user can do something, I would need to check not only the permission but that the model_has_role has the right instance of the project. But, most of the methods that do that in the package appear to be on traits or in other places I'm not so clear on how to tinker with. 

Some things I'm thinking of:

- Pulling the restrict_to morphs up to the role level. So, you could have a role that's admin for the divers project and a role that's admin for the scaffolding project, and maybe another admin for a different project as well. I'm not 100% sure that will help much. For example, the scopeRole in the HasRole trait would need to be updated to also include the restrict_to morph checks. 

- Ditch the package, keep the migration set-up, but just do the checks via the Laravel policy stuff. Because I've done this way before, I'm more comfortable with it, but that might not mean it's the best approach. For me, it would probably be faster to set up, but I'm not sure about maintaining it and for the other dev to get on board with. 

- Make my own package building off of this package. (This is probably the most terrifying option to me, because I've not done it before.) :)

Any thoughts or suggestions or questions welcome.

**Comment by hrabbit** [comment]
@llhilton Okay, only blurbed over this so far but my first thought is not to mess with the models from the laravel-permission package itself (will hurt you with upgrades), instead just create a migration that adds the extra columns to the existing database tables.

I'm trying to get a sense of your security model, and I think I can see where you are going with it. I do question what happens when you want to a allow a role to have access to something more finite than a class though. (Alas, not the conversation at hand, just an observation).

Actually, I think we might be going about this all wrong. The package already has model_has_permission and model_has_roles which would allow a single user to be related to the model itself.

```
sp1@localhost:sp1> select * from model_has_roles;
+-----------+------------+-----------------+
|   role_id |   model_id | model_type      |
|-----------+------------+-----------------|
|         1 |          1 | App\Models\User |
|         3 |          1 | App\Models\User |
|        13 |          1 | App\Models\User |
|        11 |          1 | App\Models\User |
|         7 |          1 | App\Models\User |
|        11 |          5 | App\Models\News |
|         7 |          5 | App\Models\News |
|         9 |          5 | App\Models\News |
+-----------+------------+-----------------+

```

With that logic, a user (App\Model\User::find(1) in this instance) is attached to the role_id of X.
And... **this is the part you want** App\Models\News also has rights which can be used to restrict access from other models (Roles) based on permissions.

Example of the news model with roles

```
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class News extends Model
{
	use \Spatie\Permission\Traits\HasRoles;
	protected $table = 'news';
	protected $guard_name = 'web';
}
```

**Comment by llhilton** [comment]
So, replace News with Projects. We have coordinators and dispatchers on each project, and on each project, those roles would have different permissions. For example, a coordinator might be able to view, approve and reject an application, but a dispatcher can only view them on one project. But on another project, a coordinator can view, approve, and reject, and a dispatcher can, as well.

So a project can't have permissions by itself via model_has_permission, because they need to be different depending on the role, but the role can't just have permissions by itself via role_has_permission, because they need to be different depending on the project. 

The more I chew on this, the more I think it will just make sense to add a project_id to the roles table. That will be needed to create and differentiate the role (ie project A admin vs project B admin). But then they're just different roles, even if they're both called "admin." Then the user is assigned to a particular role, and the package will work as expected. 

So, erm, I may have totally over-thought this before. As is my usual MO. :D Now to see how the implementation of this will look!

**Comment by hrabbit** [comment]
@llhilton I think you are right about looking at this too much and over thinking it. I think what you really want is just a pivot from your user table to your project table with a role_id column.

Assigning a user to a project is then as easy as selecting the role you want assigned and linking the 3 places together. As for checking permissions on your model, you would need to write a couple of methods to check permissions themselves but you might be able to deal with that in a global scope in the project model itself. If you want blade directive then you can add them also.

Sorry it took me this look to understand your requirement, every time I read the details I would confuddle (real word right?? :wink:) myself.

**Comment by IlCallo** [comment]
This is something I implemented a while ago for myself but wasn't accepted by the maintainers #292

I'll propose to add this in v3 version of the package, fell free to copy the code or take some insights

**Comment by llhilton** [comment]
Thanks everybody for the help on this! Looks like I've got it working as needed, so I'm going to close the issue.

**Comment by satishnreddy999** [comment]
> Thanks everybody for the help on this! Looks like I've got it working as needed, so I'm going to close the issue.

Hi, i also added extra field in model_has_roles table . but error return and stating that column not found, can u please help me how u resolved it?
