### ISSUE TITLE
Can I use this package without your database?

### ISSUE THREAD

**Issue by nlamblin** [spatie/laravel-permission#603]
I asked this question because I already have a role table on my database, `Status(statusId, statusName)` and I can't change it.

I don't know if it's dreamy but I hope do something like this:
```
$user = Auth::user();
$user->assignRole('a_role_name');
```

And use the role to protect routes and display content or not on .blade.php file.
Thank's for help!

**Comment by drbyte** [comment]
Hi,
To use a different database table and structure, you would have to extend the package by writing an adapter that overrides all the lookups done to the package's tables and have it read and translate the meaning from your own tables. 

You will notice that the config file names the tablenames, but that's only part of the matter: you have to change the Role model and related traits because your table structure and field-name-meanings are different.

**Comment by introwit** [comment]
Thanks @drbyte :)
