### ISSUE TITLE
Role based viewing other models

### ISSUE THREAD

**Issue by Cannonb4ll** [spatie/laravel-permission#612]
Currently using this package in several Laravel projects, loving it, great work. But I have came across a new use-case that I am not really sure on how to solve this.

I have a customer that offers downloads on his website (Download model), but he wants the ability to say; 'You need to have this role for this download to be able to download', how would I go about showing downloads to users that 'have' the required role for that download?

My customer wants to be able to select roles whilst creating or editing that are allowed to see and download this role.

Thanks!

**Comment by GioChocolateBro** [comment]
+1

Want to do the same for my page module. "only these roles can view this page"

In the process of solving this by making it myself.

Going to make a new pivot table to set the page id ( and the role id.
Then I'll make a authorized function thats called just before loading the page that will check if this page has any roles in the pivot, if so check if the user has these roles too. 
If not ill throw a 403.

Seeing as you can include the trait on other models beside the user model you can probably solve this differently.

**Comment by rohithmeethal** [comment]
@Cannonb4ll I usually check for permissions instead of roles to determine authorization.

That is instead of 
```php
if($user->hasAnyRole(['admin','paid user'])) // check if user can download song file
```
I would prefer 
```php
if($user->can('download song file')) 
```
Which is way cleaner than the first one.

Now coming back to your usecase, you wont be able to use a generic permission  predefined to check if user can download the file. Instead of that let us create permissions for specific resource.

At the time of creating a resource (her example Song resource) I would generate a permission for the download for the specific song
```php
$song = Song::create(['name'=>'Gagnam Style','file'=>'a7623hfgf.mp3']);
Permission::create(['name'=>"download song file::$song->id"]);
```
Now your decides which all roles can download the specific song, so what we just have to do is give permission to the selected roles.
```php
$songPermission = Permission::findByName("download song file::$song->id");
$songPermission->roles()->sync(Request::input('download_allowed_role_ids'));
```
Now on downloading action you just have to check
```php
if($user->can("download song file::$song->id")) 
```
Also if you want to say which roles can download the song just check which all roles are given the specific permission
```php
$songPermission = Permission::findByName("download song file::$song->id");
$downloadAllowedRoles = $songPermission->roles;
```
@GioChocolateBro  I think if you follow this way you wont need to create another pivot table

**PS:** dont forget to delete the permission, when you delete the resource

**PPS:** Thanks for this question, since this usecase made me clear why dynamically creatable permissions are useful.

**Comment by rohithmeethal** [comment]
I don't think my suggestion above https://github.com/spatie/laravel-permission/issues/612#issuecomment-354566249 is a right method to deal with the usecase, I think you should go ahead and create a table to link the resource and resources instead.

**Comment by Cannonb4ll** [comment]
I currently have this solved in another way. I just made the Download model also Roleable and I am syncing the roles to that specific model.

Then I just check in a global function inside the Download model if the user is permitted to see the file.

Basically, Downloads also have roles and I compare them with the User's roles.
