### ISSUE TITLE
Make cache optional for permissions ?

### ISSUE THREAD

**Issue by rohithmeethal** [spatie/laravel-permission#613]
Should we make cache of a permission optional, since permissions can be made dynamically this might lead to numerous permissions in some cases. For example check this issue https://github.com/spatie/laravel-permission/issues/612 and my suggestion https://github.com/spatie/laravel-permission/issues/612#issuecomment-354566249 .

What if, at the time of creating permissions user can decide which all permissions are cachable and which are not like :

```php
Permission::create(['name' => 'download file:1', 'cache'=>false]);
Permission::create(['name' => 'download any file', 'cache'=>true]);
```
So that only permissions explicitly mentioned to cache,needs to be cached.

**Comment by drbyte** [comment]
NOTE: This creates a lot more overhead because the retrieval of permissions would have to load both from cache and from the entire permissions table, and then intelligently combine them while also considering clashes.

It makes me wonder whether using roles/permissions in the way you are proposing in #612 is really the best approach? It seems unnecessarily granular by forcing the pivot of ALL records in a given model into the Gate ... thus making ALL gate operations everywhere in the site, even on other models, be forced to wade thru everything added for that other model.

**Comment by rohithmeethal** [comment]
@drbyte I think you are right, even I had my doubts if this is right way to approach the solution. Closing this issue 👍
