### ISSUE TITLE
Permission Middleware Breaking in Laravel

### ISSUE THREAD

**Issue by billabrian6** [spatie/laravel-permission#634]
I'm trying to use the permission middleware on a route in Laravel 5.5, but it breaks on this piece of code.

`app('auth')->user()->can($permission)`

The can method to be specific, but works if changed to:

`Auth::user()->hasAnyPermission($permission)`

This issue is happening in version 2.8, and the code can be found [src/Middlewares/PermissionMiddleware.php](https://github.com/spatie/laravel-permission/blob/master/src/Middlewares/PermissionMiddleware.php).

**Comment by drbyte** [comment]
"Where" in your app is it breaking? In the app? or in tests? 
Is it related to a specific guard? 

Please share your model's code and the code that's firing that middleware.

**Comment by billabrian6** [comment]
It is breaking on page load, and using the default guard 'web'.

This is how I'm using the middleware:
```
Route::group(['middleware' => ['auth', 'permission:view']], function () {
    Route::get('/', function () {
        return Redirect::route('dashboard.index');
    })->name('dashboard');
}
```

Laravel error says undefined method call, but if I replace it with hasAnyPermission it works.

**Comment by drbyte** [comment]
Quick check: does changing to version 2.7.9 instead of 2.8.0 make any difference?

`composer require spatie/laravel-permission: "2.7.9"`

I don't think it's related, since the change in 2.8.0 was related to guards, but it's worth checking to be sure. 


Is this on the User model? In what ways has your User model been altered from Laravel default? 
How has your config/auth.php been altered?

**Comment by billabrian6** [comment]
I was only meaning to say that I'm using 2.8.0. My wording my have been confusing, sorry to make it seem like I was blaming that version. I did still attempt to use 2.7.9, but the issue is the same.

My User model has a few hasOne/hasMany methods and a 'saved' event.

auth.php has been modified to use ldap:

```
'providers' => [
    'users' => [
        'driver' => 'adldap',
        'model' => App\Models\User::class,
    ],

    // 'users' => [
    //     'driver' => 'database',
    //     'table' => 'users',
    // ],
],
```
Issue:
`"Call to undefined method Illuminate\Database\Query\Builder::can()"`
```
     * @param  string  $method
     * @param  array   $parameters
     * @return mixed
     *
     * @throws \BadMethodCallException
     */
    public function __call($method, $parameters)
    {
        if (static::hasMacro($method)) {
            return $this->macroCall($method, $parameters);
        }
 
        if (Str::startsWith($method, 'where')) {
            return $this->dynamicWhere($method, $parameters);
        }
 
        $className = static::class;
 
        throw new BadMethodCallException("Call to undefined method {$className}::{$method}()");
    }
```
Do you think using ldap is contributing to the issue?

**Comment by billabrian6** [comment]
If I roll this package back to 2.5.1 it works great, but I'm sure I losing some good functionality going that far back.

**Comment by drbyte** [comment]
> If I roll this package back to 2.5.1 it works great, but I'm sure I losing some good functionality going that far back.

That's interesting. 2.5.2 changed the middleware to use the cached permission data.
So that suggests to me that your app has middleware dependencies or alterations that are interfering. 
Or that your application's `Gate` infrastructure has been altered such that the way this package leverages it is incompatible with your app.

> "Call to undefined method Illuminate\Database\Query\Builder::can()"

The `can` method must be fired on the `User` objection, not on a query.  
The fact that your error message shows that you've got a `Query\Builder` object, it suggests that something has changed the compatibility of the normal `app('auth')->user()` response signature ... which is actually alarming.  


Without seeing all of your app's code, there are a lot of unknowns here. 
I suppose you could try turning off package-discovery by specifying this package in `dont-discover` in `composer.json`, and then manually register this package in your `config/app.php` AFTER all your other app dependencies, basically as the last item in that array. Not sure if a load-order change will resolve any conflicts with other packages' alterations. It did for another one that had different caching dependencies.

**Comment by billabrian6** [comment]
We are using ldap to authenticate with active directory using [Adldap2-Laravel](https://github.com/Adldap2/Adldap2-Laravel).

This is the only thing I can find may do what you've suggested.

**Comment by billabrian6** [comment]
Updating to the newest version of [Adldap2-Laravel](https://github.com/Adldap2/Adldap2-Laravel) fixes the issue. @drbyte, thanks for trying to help me fix the issue!
