### ISSUE TITLE
user and role single result for eloquent relationship

### ISSUE THREAD

**Issue by t0n1zz** [spatie/laravel-permission#672]
hi, first of all i love your package and you really do a great job. So after trying to use the role features i find out that when i do this
```

	public function index()
	{
			$table_data = User::with('CU','pus','roles')->select('id','id_cu','id_pus','name','username','gambar','status','created_at')->filterPaginateOrder();
			
    	return response()
			->json([
				'model' => $table_data
			]);
	}
```

it gonna return collection of roles that associated with the user because this package can make a user with a lot of different roles. But in my project i just need single role for each user and because of that i want to return a single roles name for each user...

well i can manage that by using foreach when rendering. but i have some trait that called `filterPaginateOrder()` that enable me to do some advance searching or grouping to each column that avaiable.

to do that, for example i have relationship

```
public function CU(){
        return $this->belongsTo('App\CU','id_cu','id')->select('id','name');
    }
```
and it mean to do searching i just use CU.name as the `search_column` for my trait to works...

But i have no idea how to make it work with `roles`, i tried `roles[*].name` or `roles.name` and it just not working maybe you can give some direction to this?

**Comment by drbyte** [comment]
You may want to explore overriding the [`roles` method from the trait](https://github.com/spatie/laravel-permission/blob/master/src/Traits/HasRoles.php#L30-L39) by copying it into your model, and customizing it in a similar way as your `CU()` method.
Granted, it's a MorphToMany instead of a BelongsTo relationship, so may require some different handling. 

You could also copy it over with a different name like `roles_custom`, so that the original `roles` trait can still function as-is, and make your changes to `roles_custom` without negatively impacting other parts of your application. Then "use" it via `with('roles_custom')` instead of `with('roles')`.

**Comment by t0n1zz** [comment]
hmmm sorry i don't quite understand how it is works like what you explained...

**Comment by drbyte** [comment]
First, I do NOT know if this will give you what you're looking for.

But what I was trying to suggest was adding something like this to your model along with the `HasRoles` trait which you've already added:

```
public function roles_custom(){
        return $this->morphToMany(
            config('permission.models.role'),
            'model',
            config('permission.table_names.model_has_roles'),
            'model_id',
            'role_id'
        )->select('id','name');
    }
```

And then instead of `with('roles')`, use `with('roles_custom')`.

**Comment by t0n1zz** [comment]
hmmm sorry but what i really wanted it to make it not returning an array but a single object only just like what we always get when using belongsTo relationship...

**Comment by drbyte** [comment]
@t0n1zz Have you tried just adding a `MorphOne` relationship?
