### ISSUE TITLE
Request [v3] roleMiddleware support guards from other middleware

### ISSUE THREAD

**Issue by bitbirddev** [spatie/laravel-permission#684]
Imagine a Route-Group like this

```php
Route::prefix('v1')->namespace('Api\\v1')->middleware(['auth:api', 'role:admin'])->group(function () {

    Route::apiResource('users', 'UserController');

});
```

and the default laravel-permission middleware
```php
class RoleMiddleware
{
    public function handle($request, Closure $next, $role)
    {

        if (Auth::guest()) {
            throw UnauthorizedException::notLoggedIn();
        }
        $roles = is_array($role)
            ? $role
            : explode('|', $role);

        if (! Auth::user()->hasAnyRole($roles)) {
            throw UnauthorizedException::forRoles($roles);
        }

        return $next($request);
    }
}
```

now if i request /api/v1/users it checks if the current $user hasAnyRoles() but this function doesn´t respect the current guard. so if i´ve a  role 'admin' for guard 'web' this middleware will pass... but it shouldnt because the request lives in the 'api' guard.

It would be better if only the roles of the current guard would be loaded.

**Comment by drbyte** [comment]
Currently this package treats the model's $guard property as the authority, not the `config` array.

However, as you point out, Laravel treats the `config` as the guard authority ... because it has no knowledge of model-specific rules:
https://github.com/laravel/framework/blob/5.6/src/Illuminate/Auth/Middleware/Authenticate.php#L39-L62
https://github.com/laravel/framework/blob/5.6/src/Illuminate/Auth/AuthManager.php#L186-L212

Others have reported similar confusion, and usually have fixed it by specifying a guard on the model ... at least where that works for them in their specific app.

Changing this would be a breaking change, so I've marked it for v3 consideration, as I think we need to review and make adjustments for this to work more seamlessly.

**Comment by bitbirddev** [comment]
Thanks for your answer! Understood. Looking forward to see this functionality in V3! Keep up the good work!

**Comment by hafael** [comment]
A gambiarra come solta...

`
trait HasGroupRoles
{
    use HasRoles;

    public function hasRole($roles): bool
    {
        
        $teamRoles = $this->teams->map(function($team){
            return $team->roles;
        })->collapse();

        if (is_string($roles) && false !== strpos($roles, '|')) {
            $roles = $this->convertPipeToArray($roles);
        }
        if (is_string($roles)) {
            return $teamRoles->contains('name', $roles);
        }
        if ($roles instanceof Role) {
            return $teamRoles->contains('id', $roles->id);
        }
        if (is_array($roles)) {
            foreach ($roles as $role) {
                if ($this->hasRole($role)) {
                    return true;
                }
            }
            return false;
        }
        return $roles->intersect($teamRoles)->isNotEmpty();
    }

}

`
provisionally works for me
