### ISSUE TITLE
Does the package prevent the use of simple Authorizable models?

### ISSUE THREAD

**Issue by mr-mmmmore** [spatie/laravel-permission#694]
Hi,

The package is great, I have added roles and permissions to my site in less than two hours! The API is easy and very versatile. Many thanks for such value!

However, it seems that the package has broken the ability to use can/cant on a model that is only Authorizable.

I have added the roles and permissions to my User model and this part works fine. But I also have a Subscriber model which only implements Authorizable and uses the Authorizable trait in order to benefit from the can/cant methods. This part is now broken: when the can method is called on the Subscriber model, I get this Error:

```
Type error: Argument 1 passed to Spatie\Permission\PermissionRegistrar::Spatie\Permission\{closure}()
must implement interface Illuminate\Contracts\Auth\Authenticatable,
instance of App\Models\Subscriber given,
called in /home/vagrant/Code/laravel/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php on line 314      
```
The before callback implemented in PermissionRegistrar makes the assumption that the passed $user is an Authenticatable, this is what breaks my call to the can method on my Authorizable model. 

I am not a specialist of Gates, but as far as I understand, any call to the Authorizable methods will pass through any callback that have been registered on the gate. So enforcing Authenticatable here will break any call to can on a model that is not an Authenticatable but is legit to use can.

Also, I see no use of any of the Authenticatable methods in this callback, so why is it enforced here? This restriction seems to be recent, it was added in 1f98264.

If I remove this Authenticatable type hint in the callback it works again, but I wanted to be sure, am I missing something here?

BTW, I am using Laravel 5.4 and laravel-permission 2.9.2.

**Comment by drbyte** [comment]
@mr-mmmmore wrote:
> Does the package prevent the use of simple Authorizable models?

No, it doesn't intentionally prevent that. To adjust for supportability of that, can you post a repo of your app code so we can use it for testing? (feel free to simplify/remove parts that aren't related to this auth requirement)

**Comment by elghobaty** [comment]
Well @drbyte, I think what @mr-mmmmore is trying to say is that the package always assumes that the model which is being assigned roles/permissions (e.g. `User`) implements the `Authenticatable` contract. This is not always the case. For example, imagine a system where you have user groups, a user group is not necessarily `Authenticatable`. Laravel itself adds its authorization method, i.e. `can` to the `Authorizable` trait. 

We are facing the same issue btw, so, in short, I believe that you might need to consider using `Authorizable` instead of `Authenticatable`.
https://github.com/spatie/laravel-permission/blob/b48ff36ef047475327ec6ebcc383f38194cfb592/src/PermissionRegistrar.php#L31

**Comment by drbyte** [comment]
Yes, good point. 
I'd be open to a PR for that change.
