### ISSUE TITLE
@can('permission') see model_has_permission only?

### ISSUE THREAD

**Issue by sadalsuud** [spatie/laravel-permission#702]
HI, I have a role with a permissions, but I do @can('add_user') not work, and if I add add_user permission into model_has_permission, @can('add_user') work. 

My question is if @can('permision') see role->persmission or permision into model_has_permission. 

I am use Laravel 5.5

**Comment by drbyte** [comment]
1. If you are manually inserting records into the tables, then you need to also manually clear the cache.
You should NOT be manually editing the database. Use the methods provided in the README.

2. The `$user->can()` and blade `@can()` function similar to the `$user->hasPermissionTo()`, but they do it using the Laravel Guard infrastructure so that permissions are registered very early in the bootstrap process. If you have other guards or middleware that are interfering then you may get unexpected results.
