### ISSUE TITLE
Controller Middleware on L5.6 :

### ISSUE THREAD

**Issue by AEK-BKF** [spatie/laravel-permission#707]
Hi,
I'm trying to use middleware into my controller, but it always returns true !

Here L5.6 docs : 

```
public function __construct()
    {
        $this->middleware('auth');

        $this->middleware('log')->only('index');

        $this->middleware('subscribed')->except('store');
    }
```

So I use yours :

```
public function __construct()
    {        
       $this->middleware('permission:listYears')->only('index');       
    }
```

It returns true :/

Thanks for help.

**Comment by drbyte** [comment]
Can you put your code up into a github repository for further inspection?

**Comment by AEK-BKF** [comment]
Thanks for answer,
Unfortunately I can't, but the code works fine if i put a role in the middleware instead of permission.
Like this :

```
public function __construct()
    {        
       $this->middleware('role:Inst Manager')->only('index');       
    }
```

It works fine, but if I put only permission, it always returns True.

NB: In my conception, I can give to user both roles and permissions, or just permissions.

**Comment by drbyte** [comment]
Perhaps you have a global gate policy registered to always return true? 
eg: https://github.com/spatie/laravel-permission/wiki/Global-%22Admin%22-role

**Comment by drbyte** [comment]
I'm convinced there's something at the app level that's causing your undesired outcome.
Simply adding either a permission or role middleware to the controller works as expected -- example at: https://github.com/drbyte/spatie-permissions-demo/commit/5ebbcbe2910581c3bdca25ecbc28d3f413dcddb4 (you can see in the example that I've included both a role and permission middleware (associated with the seeded data); only one is needed; and if you change the role to `admin` instead of `writer` then the appropriate exception is thrown.)
