### ISSUE TITLE
Extending problem

### ISSUE THREAD

**Issue by pscom** [spatie/laravel-permission#743]
Hello guys!

I tried to extend the Role and Permission model but something isn't okey. When i created my versions and extends Role from package i cannot use _crete_ method or simple _save_ because i had error

> Field 'name' doesn't have a default value

I have _$filled_ attribute in my new class. 

Can you help me with this? I think that i must extend original model because i want to use this package to translate it: https://github.com/dimsav/laravel-translatable

**Comment by drbyte** [comment]
When extending you must still be certain that your code provides a `name` field to the model, as it is a required field. Even if you translate it to something else via a related table, you must still provide a `name`, since that `name` is what the code uses to do all its lookups for authorization activities such as middleware and hasRole() etc calls.
So, while you may wish to translate the name of a role for "display to the user" in various languages, you must still assign a primary `name` which is stored in the model.
