### ISSUE TITLE
Issues with middleware when using role and permissions

### ISSUE THREAD

**Issue by JPT62089** [spatie/laravel-permission#761]
Hello!

I'm having issues with using the Route::group middleware to grant access to a user that is either in the super-admin role OR has a specific permission (but not in the super-admin role). However, it seems as tho it's treating this as a role AND permission...

**web.php**
```
Route::group(['middleware' => ['role:super-admin', 'permission:edit events']], function() {
    Route::resource('events', 'EventController');
});
```

Does anyone know why it's doing this? It seems as tho the [README.md](https://github.com/spatie/laravel-permission#using-a-middleware) suggests that this should be an OR not AND...

**Comment by drbyte** [comment]
Hi @JPT62089,
I see where the confusion exists. Yes, the README examples do kinda suggest an "OR" operation.

However, Laravel's middleware operates as AND when you specify multiple middleware rules. (That's why there are the `except()` and `only()` methods chainable when declaring middleware in the controller.

A couple workarounds:

1. Write a custom middleware which provides the OR check for the conditions you mention. Perhaps you might call it `roleOrPermission` and then you'd call it like this:

```diff
-Route::group(['middleware' => ['role:super-admin', 'permission:edit events']], function() {
+Route::group(['middleware' => ['roleOrPermission:super-admin,edit events']], function() {
```
 It would receive `super-admin` as the first additional parameter, and `edit events` as the second. Then your middleware logic would need to check those in an OR fashion. See [middleware parameters](https://laravel.com/docs/5.6/middleware#middleware-parameters) in the Laravel docs.

2. A potentially simpler approach would be to treat Super-Admin as an "everything" role, and then it will always receive `true` from permission-checks (ie: `can`). An example of that is in the Wiki: https://github.com/spatie/laravel-permission/wiki/Global-%22Admin%22-role

**Comment by JPT62089** [comment]
Thank you, @drbyte! I completely missed the Global Admin role in the wiki. I will look into that as that's essentially what I was trying to accomplish :D
