### ISSUE TITLE
Determine if a model has all permissions

### ISSUE THREAD

**Issue by SamuelNitsche** [spatie/laravel-permission#765]
First of all thanks for this package, it helps me a lot!
I am wondering if there is a way to determine if a model has all permissions like the method `hasAllRoles`. I could not find something like `hasAllPermissions`.
Thanks!

**Comment by drbyte** [comment]
Not at the present time.

Can you describe the scenario you're working with and the problem you're trying to solve?

**Comment by drbyte** [comment]
I see your point.

When I run into this sort of scenario it makes me strongly lean towards abstracting that combination of permissions into a policy. This way I can also name it something semantic (which also encourages me to consider additional opportunities elsewhere in my code).

One thing you could do in the short term is change `hasPermissionTo()` to just `can()`, since all permissions are pushed into the Gate so calls to `can()` and `@can()` can be used in your code and templates respectively.

**Comment by drbyte** [comment]
We're happy to review all pull requests! Especially those that are explained well and include supporting tests.

While you're coding ...
One thing to keep in mind about permissions (that's different from roles) is that since roles currently support only one tier, the "hasAnyRole" is a very simple lookup. But permissions might exist in other roles held by the user/model. 
While simply making `hasAnyPermission($permissions)` do a looped lookup is "one" way to tackle it, there may be a more performant solution that could be explored.
