### ISSUE TITLE
Upgrade Guide?

### ISSUE THREAD

**Issue by TaylorFoster90** [spatie/laravel-permission#771]
Hello!

Working on a team that aquired a project that is using this extension for permissions. 

We want to go from `1.3` to the most stable version. Is there an upgrade guide I can follow?

**Comment by drbyte** [comment]
It was decided in the design process for building v2 that there would NOT be any clear upgrade path provided.

That said, in my experience, the way to upgrade is to build a simple extraction of all roles and permissions, along with which users are assigned to those roles/permissions, and then re-build and re-assign all those roles, permissions, and users-and-relationships.  
On a couple smaller apps with limited number of users and roles/permissions I found this was a quick exercise.
On a couple much larger apps, I've found that sticking with v1.x has been perfectly satisfactory.
(And indeed that's why I've been keeping the v1.x branch compatible with later Laravel versions, instead of letting it die completely.)

The primary missing "feature" in v1 is that v2 added additional support for model-specific-guards. If you don't need that feature, there's less compelling reason to upgrade.
(And in fact for v3 there's a very strong likelihood that the guard-specific code will be removed.)

Hope that's helpful.

**Comment by TaylorFoster90** [comment]
@drbyte figured out my issue. Closing.

**Comment by drbyte** [comment]
@TaylorFoster90 Glad you got it sorted out. Was the issue you ran into something that might be useful for others to understand as a possible gotcha?

**Comment by fabricecw** [comment]
I wrote a migration script for V1 to V2.28. If someone wants to upgrade from V1 to V2, my [3
Update spatie/laravel permission tables from V1 to V2](https://gist.github.com/fabricecw/58ee93dd4f99e78724d8acbb851658a4) Gist.

**Comment by drbyte** [comment]
Thanks @fabricecw !

**Comment by FrittenKeeZ** [comment]
I just created a [migration script](https://gist.github.com/FrittenKeeZ/80772b6b37b2b56bfee0d912f4ad2118) for those only using roles, which also works with rollbacks.
I'm pretty sure it can be modified to handle permissions as well.
