### ISSUE TITLE
Unable to give permission directly to a user 

### ISSUE THREAD

**Issue by itsmekps** [spatie/laravel-permission#816]
i m trying to give permission directly to a user,
```
$user = User::where('ref_id', '=', 112)->first();
$user->givePermissionTo('add student');
```
after executing the above code i can see a extra row added in the table "model_has_permissions" but still when i try to access the following:

```
if($user->hasPermissionTo('add student'))
{
   return view('admin.student');
}
```

it shows me error "User does not have the right roles"
and one more thing i didnt assign the permission to the role to which this user "112" belongs to (_bcoz in doc its written "A permission can be given to any user"_) so if this is the problem pls shed some light on me or tell me what else i m doing wrong

**Comment by drbyte** [comment]
Hmmm ... what you did is correct: 

```php
$user = User::where($foo, $bar)->first();
$user->givePermissionTo('add student');
$user->hasPermissionTo('add student'); // should give true
```

However, if you're doing it via Tinker then you have to exit Tinker before running the `hasPermissionTo` since the cache gets changed during the `givePermissionTo` and Tinker won't see it until it is restarted. 
Similarly, your app in the browser won't see it until the "next" request cycle.

**Comment by itsmekps** [comment]
no i am not doing it via tinker i have just written that code in the controller function and hitting the corresponding route for that function in browser...

so now what .............. do i have a hope or not ??

**Comment by drbyte** [comment]
In a typical app you will do the "giving" and the "checking" in two separate requests, right? 
ie: in some Admin panel you'll "give permission to" someone for something.
Then that user will login in another browser session and attempt to "view" the specified page.

Doing both the giving and checking inside the same controller method may give unexpected results because the cache gets a reset during the "give" call.
I gather you're just testing how it works, and I completely understand that it's convenient to drop a bunch of sequential commands into a single controller method. But that won't work in this case. (We're considering simplifying this specific thing in v3 though!)

**Comment by itsmekps** [comment]
@drbyte i really appreciate the support provided by you but "giving permission" and "checking permission" i am doing these two things in two different requests.

And yes i am doing the both things giving and checking in the very same controller but not in same method.

```
public function index()
{			
	$user = User::where('ref_id', '=', 112)->first();
	$user->givePermissionTo('add student');
}

public function student()    
{		
	$user = User::where('id', '=', Auth::user()->id)->first();
	if($user->hasPermissionTo('add student'))
	{
		return view('admin.student');
	}
	else
	{
		abort(404);
	}
				
}
```
above both methods are in the same controller.

**Comment by itsmekps** [comment]
sorry @drbyte , i am really sorry that was totally my fault the route i was hitting  was filtered by role admin,
once again i m really sorry for your precious time

**Comment by drbyte** [comment]
No worries -- been there, done that myself!
