### ISSUE TITLE
Assign Roles to Unauthed user...

### ISSUE THREAD

**Issue by xJoeyv** [spatie/laravel-permission#826]
Hi,

I want to assign a role to a User that is a guest ( Not authenticated ) this role can be Guest or Banned based of there IP that is been blacklisted or not.

How can I assign or use a 'Role' to someone that is not authenticated?

**Comment by drbyte** [comment]
This package focuses on Authorization, not on Authentication.

To handle Authentication, simple do your app's authentication checks before triggering features related to Authorization provided by this package.

For example:

1. Is the user a guest? (not authenticated yet) (Laravel's own Auth functions for that)
2. Is the user banned? (use your own app's functions for this, or another package, whatever)
3. Then if it passes both of those and you log them in, then check for roles/permissions to authorize access to corresponding abilities.

**Comment by xJoeyv** [comment]
@drbyte Hi and thanks for your response.

What I meant is if the _visitor_ of the website is not **authenticated** that means he has a **guest** role when his IP is not blacklisted. Followingup he is not authorized to visit page_x. 

Only _visitors_ that are authenticated and are now _users_ with a role that contain permissions are allowed to visit that page_x and if the have the right role they are authorized .

So mine question is can I add permissions to a guest. So I can authorize and de-authorize them from doing things or viewing things.

**Comment by drbyte** [comment]
No, with this package you cannot add permissions/roles to a non-authenticated User, ie: guest.
This package can only provide permission/role verification associated with actual registered users. This is because it creates a database pivot entry associated with the model ID number of the indicated user. A not-logged-in guest is not associated with a User record.

So, to provide what you're looking for, you need to handle guest-only access-control in your app at a point before you check for Authorization provided by this package. A policy might be the ideal way to centralize the code for this and thus keep your controller cleaner, but that's entirely your choice.

**Comment by xJoeyv** [comment]
@drbyte Thanks for your Reply.

Alright then I know that about the policy etc I need to take a look then how I go and resolve this. But thanks for explaining this. I hope I will get there
