### ISSUE TITLE
How to retrieve particular user roles?

### ISSUE THREAD

**Issue by periyasamy25** [spatie/laravel-permission#842]
I have got user roles by using this getRoleNames() but i need to get particular user role.
for example user1 has student, volunteer, admin these roles
i want to get user roles other than student ie admin and volunteer roles only

**Comment by drbyte** [comment]
You can get a collection of all roles assigned to a user via `$user->roles` relation. Then filter out the ones you aren't interested in.

**Comment by paulcanning** [comment]
This doesn't work for me.

```
       $user = User::find($id);

        dd($user->roles);
```

the dump is empty, despite the user having an assigned role.

**Comment by drbyte** [comment]
@paulcanning wrote:
> the dump is empty, despite the user having an assigned role.

Without more context of your app and how you are running that code, it's hard to give a concrete answer. Lots of unknowns when trying to respond to 2 lines of code.

Things to consider:
- maybe the cache is outdated because you assigned the role with bespoke code instead of calling the provided functions
- while your example shows an immediate `dd()` call after querying the `User`, if you're actually also doing other things in between the lines of code you quoted, maybe the retrieved object needs a `->fresh()` call against it to retrieve assignments you've done in the meantime?
- calling `->getRoles()` on `$user` will run this package's functions to do the actual retrieval, instead of writing your own bespoke code to query things

**Comment by aadriantech** [comment]
This retrieves the assigned roles to the current logged in user, plucks the role name and converts to an array

dd(Auth::user()->roles->pluck('name')->toArray());

**Comment by HashmatWaziri** [comment]
Further filter: 
Auth::user()->roles->where("name","parent")->pluck('id')->toArray()

**Comment by isgtakip** [comment]
$user = $request->user(); 
return response()->json(new UserResource(User::findOrFail($user->id)));

and user resource

<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class UserResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'email' => $this->email,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
            'roles' => $this->getRoleNames(),
            'permissions'=> $this->getAllPermissions()->pluck('name')
        ];
    }
}
