### ISSUE TITLE
Get extra field values from pivot table model_has_roles

### ISSUE THREAD

**Issue by enbermudas** [spatie/laravel-permission#849]
I've created a issue yesterday a couple minutes before getting the answer by msyeld (sorry for that) but right now i am dealing with another problem.

Even thought i've added an extra filed on my ```model_has_roles``` table, i can't get this one by calling: ```$user->roles``` and i would like to know if there is a way to get that value.

**Comment by drbyte** [comment]
You can add your own new relation for `roles` which adds a custom `withPivot` declaration in order to retrieve those extra fields.

Refs: https://laravel.com/docs/eloquent-relationships#many-to-many
https://stackoverflow.com/questions/26566675/getting-the-value-of-an-extra-pivot-table-column-laravel
https://laracasts.com/discuss/channels/eloquent/how-to-access-data-of-a-pivot-table
https://laracasts.com/discuss/channels/eloquent/laravel-52-getting-a-pivot-table-additional-attribute
