### ISSUE TITLE
jwt.auth and api roles

### ISSUE THREAD

**Issue by warlord0** [spatie/laravel-permission#854]
I'm trying to figure out how to use spatie for the role checking middleware with jwt.auth for api's.

When I add the middleware I'm getting a class does not exist message:
```javascript
{
    "message": "Class role does not exist"
}
```

I'm guessing that the middleware doesn't get applied to the api routes, but don't know how to resolve that. Any help much appreciated.

If I add the middle ware in the constructor or onto the route group it fails with the same class does not exist.
```php
    public function __construct()
    {
      $this->middleware(['jwt.auth'], 
        ['except' => ['retrieveIndividual']]);

      $this->middleware(['role:Abstract User']);
    }
```
or
```php
    public function __construct()
    {
      $this->middleware(['jwt.auth', 'role:Abstract User']
        ['except' => ['retrieveIndividual']]);
    }
```

**Comment by drbyte** [comment]
Two parts required:

1. (as you've done) In the constructor or the route.
eg https://github.com/drbyte/spatie-permissions-demo/blob/master/app/Http/Controllers/HomeController.php#L18

2. Add the middleware to your app so that it knows how to resolve `role`:
https://github.com/drbyte/spatie-permissions-demo/blob/master/app/Http/Kernel.php#L60

**Comment by warlord0** [comment]
You sir are a gent. Many thanks that nailed it perfectly.
