### ISSUE TITLE
Setting access permissions for individual entries in another model?

### ISSUE THREAD

**Issue by BrekiTomasson** [spatie/laravel-permission#859]
Assume the following:

- I've got a blog where the entries are divided up into multiple access levels (say "Guest", "Standard" and "Premium"), and that these access restrictions have to be set on a per-entry level, not category-wide or similar.
- "Guest" users can only read "Guest" entries.
- "Standard" users can read "Guest" and "Standard" entries.
- "Premium" users can read "Guest" and "Standard" and "Premium" entries.

Now; the obvious first step is to create the roles ('guest', 'standard', 'premium') and the permissions ('can read guest blogs', 'can read standard blogs', 'can read premium blogs'), and assign them accordingly. Guest role gets 'can read guest blogs', standard role gets that and its own permission, premium role gets all three permissions.

So far so good - but how do I best assign the permissions to the individual posts? I don't want to hard-code the database ID of the permission to the post entry if I can avoid it, since I don't know if the set of permissions will change in the future. Any ideas?

**Comment by drbyte** [comment]
You've identified `Users` has being a certain "type". And it sounds like the "type" is static (ie: a User can only be EITHER a guest or standard or premium.

Do `Entries` also classify as a static "type"?  ie: when a Premium user posts something, is that "post" considered permanently "premium"?

**Comment by BrekiTomasson** [comment]
Yes and no. A user can be either a guest or standard or premium, but that can change - but always just one of them. Same with a post, it can be considered guest, standard or premium - but that can also change over time. However, it can not be two different things at the same time.

Also, it's not so much the writing user's permission that decides the level of the post; think of this more as a blog written by one author to multiple audiences - an author who can post it to just the premium crowd, to the premium and standard crowd or "public" (guest, standard and premium).

**Comment by drbyte** [comment]
Okay, so if a `Post` can always only be one "kind" of post, and viewers are allowed to see things based on that one status, why not just put a field in your blog `Posts` model denoting `post_type`, and then simply use Model Policies to enforce "who" can read which kinds of posts. The Policy can do the checking about whether the active user has rights to do the kind of reading based on the Post model entry's `type`.

**Comment by BrekiTomasson** [comment]
Yeah; that's what I was thinking; I'm just not sure what kind of field to use in the `Posts` model. I can't use the word 'premium', because it doesn't map 1:1 to the permission name, and I don't want to fill every controller with a series of `if ($post->entry_level === 'premium' && $user->can('read premium blog posts')` etc...

Still; I can't think of a better way to do it than that. :/

**Comment by drbyte** [comment]
Okay, conceptually I'd call your post-levels "enums" (not in the context of storing them as a database "enum" field-type though).
To code for that in Laravel you could just use some class-constants, but instead I wholeheartedly recommend the Laravel Enum package by @bensampo :
- https://laravel-news.com/laravel-enum-package
- https://github.com/BenSampo/laravel-enum
- https://sampo.co.uk/blog/using-enums-in-laravel

I suggest: 
1. Use the Enum package concepts to store the post-type in each Post record.
2. Then use a Post Model Policy to read the Enum value of the record and check against the User's allowed permissions. This keeps Controllers cleaner.

Here's an example of adding a simple Model Policy which implements this Permissions package:
https://github.com/drbyte/spatie-permissions-demo/pull/2
And here's an update to show how to use `authorize()` calls in controllers instead of relying on `authorizesResource`. You can use either concept; this just shows that it can be done either way.
https://github.com/drbyte/spatie-permissions-demo/commit/aa90b3820020b476265a2f215a87f442bec19040
