### ISSUE TITLE
Trying to set permission but is told it does not exist

### ISSUE THREAD

**Issue by jegjessing** [spatie/laravel-permission#878]
Hi. I'm trying to set a permission that does exist in the permissions table.
I've checked the spelling more than once and it is correct.
I'm using: givePermissionTo('permission_name') and I've added the use HasRoles to the model.

Works just fine our test system but not on prod. Any ideas?
Btw trying to set the HasPermissions on the contact model ends up with an error on the user model saying;
message: "Trait method bootHasPermissions has not been applied, because there are collisions with other trait methods on App\Models\Contact"

**Comment by jegjessing** [comment]
Fixed with: https://github.com/spatie/laravel-permission/issues/590#issuecomment-352651486

**Comment by drbyte** [comment]
I'm not sure how that comment fixes a collision between traits.

But, yes, the way v2 of this package works, you must either define a specific guard for a specific model (meaning multiple models if using multiple guards), or if you are really only using one guard, then make it be the first in the config array.

If this issue is fixed for you, then you can close it by clicking below.

**Comment by jegjessing** [comment]
My bad mentioning two problems in one.
It does not fix the Trait problem but it does fix the permission does not exist which was the main problem. Closing.
Maybe I've not looked good enough, but the linked solution might be part of the documentation ?
Closing the issue

**Comment by drbyte** [comment]
Agreed. I've updated the readme to add additional clarity.

It's unfortunate that this multiple-guards complexity exists (wish we'd done it differently), but changing it is a BC break so we're waiting to a major release before tampering with it.
