### ISSUE TITLE
can we use this in php 5.6 laravel 5.4 ?

### ISSUE THREAD

**Issue by vchampanery** [spatie/laravel-permission#883]
In my system i have laravel 5.4 and php 5.6 , so can i use with package.
it give me error while installing package by composer 
i.e.     - doctrine/inflector v1.3.0 requires php ^7.1 -> your PHP version (5.6.37) does not satisfy that requirement.

how can i overcome this

**Comment by drbyte** [comment]
Use v1 of this package, not v2.

**Comment by vchampanery** [comment]
![image](https://user-images.githubusercontent.com/31303925/46170139-9be54680-c2ba-11e8-9c1d-2ede11a3cc03.png)
same error php version

**Comment by drbyte** [comment]
Since composer has already installed some packages for newer dependencies, try deleting your `composer.lock` file and your `vendor` directory first.

Then since you've said you need to only support old stuff, force it to only load packages compatible with PHP 5.6 by running: `composer config platform.php 5.6.38`

Then run `composer install` and/or `composer require spatie/laravel-permission:^1`

If it's still not working, please post your `composer.json` file contents.
