### ISSUE TITLE
Class 'App\Role' not found

### ISSUE THREAD

**Issue by hamid80386** [spatie/laravel-permission#884]
This error appeared 1 week after installing spatie/laravel-permission
but i can't find the problem, even by reinstalling the spatie

The error is:
`Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Class 'App\Role' not found"
`
I reinstalled the spatie, rebuild the autoload, clear spatie cache, rebuild configurations files and many other settings.

The error triggered after run this code in a controller:
`
if (! Gate::allows('users_manage')) {
			return abort(401);
}
`
Also i test spatie/laravel-permission v2.20 and version 2.16 , but error not solve.

**Comment by freekmurze** [comment]
The fully qualified class name of our `Role` model is `Spatie\Permission\Models\Role`. Make sure you import that namespace in every class where you're using the `Role` class.

**Comment by hamid80386** [comment]
And in Laravel 5.6.38 everything are ok, but in 5.4 we have error

**Comment by drbyte** [comment]
@hamid80386 wrote:
> And in Laravel 5.6.38 everything are ok, but in 5.4 we have error

I just created a fresh Laravel 5.4 application, installed this package, created a role and assigned your `users_manage` permission to that role, and then created a user and assigned that role to the user. Then I put your `if (! Gate::allows('users_manage')) { return abort(401); }` into the `index` method of my `HomeController`, and visited the site with the browser. It properly displayed the home page without error.

Thus I conclude there is not a problem with this package, but rather the problem is in your app.

**Comment by hamid80386** [comment]
Thank you @drbyte 
But this is better to discuss about this problem more, because in many cases we can't rebuild new Laravel project and this may has very times to do.

I have to different results in 2 computer of same repository of git with this package, in my home's computer the  when i use: _use Spatie\Permission\Models\Role;_ , i have a message that shows the class never used, and in my office's computer _use Spatie\Permission\Models\Role;_ shows class used.

So this is show that in home's computer class not introduced to Laravel, in other hand because two computers has same git repository of project, so we conclude that the problem is in anythings that are in vendor.
It may be an vendor package, a setting that are in .gitignore, any setting in .env ,etc.

I think we must reopen this issue until get a proper result.

**Comment by drbyte** [comment]
If it's related to .gitignore or .env or vendor directory, those are all things related to your app or how you've installed your app code on your home computer. 

They are not indications of a problem with this package.

If you believe there is a problem with this package, please provide complete code samples that can be put onto a fresh Laravel install in order to consistently recreate the problem. And/Or provide tests which clearly demonstrate the problem. 
We will be happy to address a problem that can be recreated using the details provided.

**Comment by hamid80386** [comment]
it seem if a permission does not exist in database , we'll get this error.

**Comment by drbyte** [comment]
@hamid80386 wrote:
> it seem if a permission does not exist in database , we'll get this error.

I tried adding `if (! Gate::allows('users_manage')) { return abort(401); }` into the HomeController@index method in this [simple demo package](https://github.com/drbyte/spatie-permissions-demo/blob/master/app/Http/Controllers/HomeController.php#L28), where `users_manage` does not exist, and it properly throws a 401 ... but no `App\Role` error.

**Comment by hamid80386** [comment]
I checked bootstrap\cache\packages.php file and found below code is missing:
`  
'spatie/laravel-permission' => 
  array (
    'providers' => 
    array (
      0 => 'Spatie\\Permission\\PermissionServiceProvider',
    ),
  ),
`

When i return this code to the packages.php , spatie-permission work without error

I added PermissionServiceProvider in config/app.php , It seems PermissionServiceProvider not register properly!

**Comment by drbyte** [comment]
Interesting. 
That suggests something strangely amuck with your app or environment. Maybe a composer problem. 

As Freek said, not an issue with this package.

**Comment by hamid80386** [comment]
> not an issue with this package
Yes, I guess too, but strange matter is that i found the only thing that remove from packages.php is spatie-permission, i found it after check gitk!

**Comment by hamid80386** [comment]
Finally I found the problem, spatie/laravel-permission has an Interference with  area17/twill package
When this package load before spatie in bootstrap/cache/packages.php App\Rule not found will be occur
So wee need to remove twill. or use of any way to load twill after loading the spatie in packages.php, i don't  know how load that after spatie
so removed twill

**Comment by drbyte** [comment]
There may be additional incompatibilities as well, since Twill has its own "roles" logic for users, managed by Enum properties: https://github.com/area17/twill/blob/1.2/src/Models/Enums/UserRole.php

The Twill folks are fairly responsive. You may be able to get them to fix whatever is conflicting if you report a clear set of instructions on how to create the problem on a new project.

**Comment by BrandonPorras** [comment]
Check the namespace of your clases, if you have a namespace for your application that can be the problem.
example

use myaplication\role;  is the correct way 
because app\role; does not exists.

**Comment by MohosinMiah** [comment]
# In my case Sometime works and sometime not works
```
[2024-02-23 10:38:22] local.ERROR: Uncaught Error: Class "Spatie\Permission\Models\Role" not found in G:\Start UP\Rayhan\couponterra_website_development\app\Models\Role.php:9
Stack trace:
#0 Command line code(1): include_once()
#1 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class \"Spatie\\Permission\\Models\\Role\" not found in G:\\Start UP\\Rayhan\\couponterra_website_development\\app\\Models\\Role.php:9
Stack trace:
#0 Command line code(1): include_once()
#1 {main}
  thrown at G:\\Start UP\\Rayhan\\couponterra_website_development\\app\\Models\\Role.php:9)
[stacktrace]
#0 {main}
"} 
```

**Comment by drbyte** [comment]
Looks like a problem in your model code. Please open a new discussion and post your code.
