### ISSUE TITLE
ReflectionFunction::__construct() expects parameter 1 to be string, array given (View: C:\xampp\htdocs\Placesv2\resources\views\comments\index.blade.php)

### ISSUE THREAD

**Issue by usetwit** [spatie/laravel-permission#887]
I've just installed the package, I have a very simple @can in my view:

```
@can('edit')
Edit
@endcan
```

`'edit'` is quite clearly a string, but yet I get the error message

```
ReflectionFunction::__construct() expects parameter 1 to be string, array given (View: C:\xampp\htdocs\Placesv2\resources\views\comments\index.blade.php)
```

Where abouts is `edit` getting turned into an array?

**Comment by drbyte** [comment]
`@can` is part of core Laravel's `Gate` features.

This package registers authorized permissions with the gate, and then when you call `@can` it simply fires Laravel's gate callbacks to test for the permission.

https://github.com/spatie/laravel-permission/blob/5415d29d54d15985b8cf56fef30d7514c8608309/src/PermissionRegistrar.php#L39-L46

Maybe your application code is conflicting due to method/permission names?
Do you happen to have a Policy defined which also provide an `edit` check?
