### ISSUE TITLE
hasRole()

### ISSUE THREAD

**Issue by elhawy** [spatie/laravel-permission#901]
$this->roles->contains('name', $roles); 
why  dd($this->roles) 
it always  = items[]

**Comment by drbyte** [comment]
You posted in https://github.com/spatie/laravel-permission/issues/250#issuecomment-292992729 suggesting that you have the same root cause as the other person posting there: your model contains a `roles` property (or db field).

If your model contains a `roles` property, then `$this->roles` will always contain what your model-property(table) has, and not what this package's polymorphic relation has.

If you want to use this package, your model must not contain a `roles` or `permissions` property or fields in the model's table.

**Comment by elhawy** [comment]
Thank for your time  . error  on guard
