### ISSUE TITLE
new cache permissions gone

### ISSUE THREAD

**Issue by universenl** [spatie/laravel-permission#927]
Hello,

I am trying to get my new web app live, but for this time i run into some trouble.
It seems when ever the storage/cache/data/85/ file is cleaned laravel spatie is not getting my admin permissions anymore. When i replace the cache file with an older one it seems to work again.

Can somebody please assist on this, already got more than 20 hours in this problem.
Added both of the cache files

[855f92484c8c414d36c1b25cb24876e30229cbbf_new but not working.txt](https://github.com/spatie/laravel-permission/files/2565805/855f92484c8c414d36c1b25cb24876e30229cbbf_new.but.not.working.txt)
[855f92484c8c414d36c1b25cb24876e30229cbbf_working.txt](https://github.com/spatie/laravel-permission/files/2565806/855f92484c8c414d36c1b25cb24876e30229cbbf_working.txt)

Greatings Mitch

**Comment by drbyte** [comment]
> It seems when ever the storage/cache/data/85/ file is cleaned

What is doing the "cleaning" of files in your `storage` folder?

**Comment by drbyte** [comment]
Well, the problem could be in 4 places:
- how your server's caching is configured
  Maybe you should switch from "file" caching to "database" or "redis"?

- your application code
  It's possible that you've got something in your code that is triggering the caching to happen against wrong data.

- this package
  Without having a complete copy of your application code in order to use it to run new tests against this package, I'm inclined to think this package isn't the problem. All its tests are passing, even when run against multiple caching drivers.

- server deployment
  Maybe something is changing the files on your server, when they shouldn't be touched.

**Comment by universenl** [comment]
Its seems like something on the production server, becouse the development still runs without any errors. Same version of the application only not in production build.

It seems like when we save a permission this error occurs right away, so if i save the permission All on the adminpanel we get locked out and the cache file is changed.

The wierd thing about this story, we did run the backend in production mode for like 6 weeks without this error occurs once. But like i sad, the development version still runs string and even there we can save the All permissions and the website still works.

**Comment by drbyte** [comment]
Ya, it seems like something odd on the server.

The package does delete cached permissions on save, but rebuilds them again on the first query.

Again, switching from file-based caching to a different cache driver may reveal something useful in your debugging process. Instead of `file`, try `array`. Then you can try `database` if you create the cache table in the db (run php artisan cache:table to create a migration for that table). If you have redis on your server, you can install `predis/predis` with composer and change to `redis` for your cache driver.

You didn't mention which Laravel version.  
What's the content of your `composer.json`?

**Comment by universenl** [comment]
This is fixed, wrong id in mysql was the problem.
