### ISSUE TITLE
Call to undefined method Illuminate\Routing\Route::macro()

### ISSUE THREAD

**Issue by AsiaCobra** [spatie/laravel-permission#935]
Hi,

Im using Laravel 5.5 and when i run this command:

`composer update `

im getting this error:
``
```
**In PermissionServiceProvider.php line 122:

  Call to undefined method Illuminate\Routing\Route::macro()


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1**
```

How can i solve this?
Thank you.

**Comment by drbyte** [comment]
I've tested by installing a fresh copy of Laravel 5.5 and then adding this package to it. It gives no errors about the Route::macro() call. Thus I believe your problem is something inside your own app.

This package assumes that your app resolves a compatible instance of `Illuminate\Routing\Route`, so perhaps the error you're getting indicates that you've bound a different incompatible instance of `Route`, either in your app or in another package you've installed.
