### ISSUE TITLE
PermissionNotExist (there is no permission with id 1)while Permission Exist in DB table

### ISSUE THREAD

**Issue by 3ubeen3** [spatie/laravel-permission#949]
Hi,

i want to assign a permission to a role.Below is my code:
MyController.php
public function testing_role_permission()
    {
      $role = Role::findById(2);
      $permission = Permission::findById(1);
      $role->givePermissionTo($permission);

    }
The role and permission exists in their tables.But i don't know why it's not working.

Before it was working but after it i added more permission in permission table by using laravel seeder class.Here is my seeder class code:

PermissionTableSeeder.php

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();
        //role permissions
         Permission::create(['name' => 'create_role']);
         Permission::create(['name' => 'read_role']);
         Permission::create(['name' => 'update_role']);
         Permission::create(['name' => 'delete_role']);
         Permission::create(['name' => 'disable_role']);
         Permission::create(['name' => 'isolation_role']);
}

Before seeding this file everything was working perfectly but it is not working after seeding this class.

Any solution please?

Thanks

**Comment by drbyte** [comment]
I just [recreated your app based only on the code you posted](https://github.com/drbyte/test3ubeen3).

First, your Seeder doesn't create any Roles, so the error is `no role exists with id 2` when your controller runs `Role::findById(2)`.
But then updating the seeder to create 2 roles allows the role lookup as well as the permission assignment.

So, *after fixing the seeder in your app, the permission assignment works*.

Also worth noting: after updating the seeder class you must re-seed your database. And, since seeders are primarily intended for fresh databases (not adding-to existing databases), it is best to also run `artisan migrate:refresh --seed` to get a clean database with fresh migrations and fresh seeding.

You can see the working app code at https://github.com/drbyte/test3ubeen3/commits/master
The README contains all the steps to recreate the app from fresh:
```sh
laravel new test3ubeen3
cd test3ubeen3
git init
git add .
git commit -m "Fresh Laravel 5.7.14"
composer require spatie/laravel-permission
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="config"
touch database/database.sqlite
nano .env # edit .env file to set database to sqlite
git add composer.json
git add config/permission.php
git add database/migrations/2018_11_21_160026_create_permission_tables.php
git commit -m "Add spatie/laravel-permission pkg"
php artisan make:seeder PermissionTableSeeder
nano database/seeds/DatabaseSeeder.php # edit to add new seeder
git add database/seeds/DatabaseSeeder.php database/seeds/PermissionTableSeeder.php
git commit -m "Add seeder"
php artisan make:controller MyController
php artisan migrate:refresh --seed
git add app/Http/Controllers/MyController.php routes/web.php
git commit -m "Add MyController"
php artisan migrate:refresh --seed
nano database/seeds/PermissionTableSeeder.php #fix seeder to add roles
git add database/seeds/PermissionTableSeeder.php
git commit -m "Fix seeder to also create the required roles"
```
