### ISSUE TITLE
Version 3 ETA?

### ISSUE THREAD

**Issue by Rux77** [spatie/laravel-permission#979]
Hello,

First sorry if I am asking this in the wrong place.. I don't know where else to put it..

I am starting a new project and I was waiting for **v3** of this package because It will remove the guards logic...

Is it gonna be released any time soon? 

thank you for your great work,

**Comment by drbyte** [comment]
There's no specific planned ETA, but I was hoping to make some noteworthy progress with some spare time over the holidays.
The biggest hurdle is in recalculating the 2nd half of the polymorphism since the guard formerly provided that because it was a hardcoded relationship.

That said, if you don't need the forced guard declarations that v2 uses, and don't need the polymorphism, v1 works fine (but it's designed for a single User model per app).

**Comment by Rux77** [comment]
I was hoping that v3 would be released soon..
Also I didn't know that v1 support latest version of laravel..

Since my question was answered, closing.. 

thank you,
